### ISSUE TITLE
Hover Maven Credentials

### ISSUE THREAD

**Issue by jumaallan** [UseHover/Stax#40]
Hi @davkutalek @ishuah @androidmaven ,

Someone would need to have credentials to access `https://pro.maven.usehover.com/snapshots`

Do you allow external contributors to have guest credentials?

**Comment by davkutalek** [comment]
@jumaallan thanks for pointing this out. We don't have guest credentials, but you can just remove the pro part from the dependency so it is like `1.7.1-stax-1.1.2`. Doesn't currently make a difference besides the transaction processing screen will look different.

We will think more about how best to make contributing easier.

**Comment by jumaallan** [comment]
thanks @davkutalek
