### ISSUE TITLE
[Bug]: Recipient network logo does not change when you move from the buy airtime page to the send money page.

### ISSUE THREAD

**Issue by Clish254** [UseHover/Stax#601]
### Description

When sending money with mpesa and the recipient is mpesa, the airtel logo is displayed instead of the safaricom logo. This happens if before going to the send money page you go to the buy airtime page and select  Pay with - M-PESA and Recipient network - Airtel.
![Screenshot_20221012-134132_Stax](https://user-images.githubusercontent.com/29974159/195325020-30665b2f-9f0b-4061-89ec-f74d0b120729.jpg)

### Steps to reproduce

1.Open stax app
2.On the home screen select buy airtime
3.On the buy airtime page select Pay with - M-PESA and select Airtel as the recipient network
4.Go back to the home page
5.Select send money
6.On the send money page select Pay with - M-PESA and select M-PESA as the recipient network
7.You will notice that the icon on the recipient network is still airtel, probably doesn't update from the previously selected recipient network on the buy airtime page.

### Expected result

Whenever a user selects the "Pay with" and recipient network, the logo of the selected network should be correctly updated even if the user selected something else previously either on the same page or on another similar page e.g buy airtime and send money in this case.

### Actual result

When I selected airtel as the recipient network in the buy airtime page then navigated to the send money page and selected M-PESA as the recipient network, the ricipient network logo didn't change from airtel to safaricom.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1bXVZIMJAMa6Qj9jxeRuXkbB23DLE22P4/view?usp=sharing

### Device name

Samsung Galaxy S21 5G

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Stax device ID or email address

8d8fbf9355646d50

**Comment by johnswekenyi** [comment]
@Clish254 thank you for creating the bug. I followed your steps above and I was unable to reproduce the bug.

**Comment by johnswekenyi** [comment]
I will leave this open for now incase someone else is able to reproduce it.

**Comment by Clish254** [comment]
This issue is still there

**Comment by Clish254** [comment]
Probably [this](https://drive.google.com/file/d/1fccC32uOB3OagmO43gA5CVUqb2n73ygt/view?usp=sharing) video will help, go to buy airtime before send money.

**Comment by johnswekenyi** [comment]
Logging this as part of #629
