### ISSUE TITLE
[Bug]: Incorrect balance is displayed when checking safaricom airtime balance

### ISSUE THREAD

**Issue by Clish254** [UseHover/Stax#602]
### Description

When checking my safaricom balance the request was successful but the displayed balance was wrong, on stax 0Ksh was shown as the balance but the correct balance was actually 38.59Ksh

### Steps to reproduce

1. Open the stax app
2. On the home page select SIMs on the navigation bar at the bottom
3. If you have a safaricom sim card find it in the list of your sim cards and select check balance
4. Once the transaction is completed click continue in the displayed dialog box and the app will take you to a receipt page.
5. On the receipt you should see your balance
6. Dial *144# on your phone and compare the balance safaricom shows you with the balance displayed by stax

### Expected result

The balance shown on the receipt after checking my safaricom balance should match the balance I get when I use the safaricom ussd code *144# to check my balance.

### Actual result

The transaction was processed successfully but the balance displayed by stax(0KSH) was different from the balance I received from safaricom(38.59KSH). Check the linked video from 1:30 mins.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1baEAEVUBI2Zvs1R-iLiERkHBhIBah_mU/view?usp=sharing

### Device name

Samsung Galaxy S21 5G

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Stax device ID or email address

8d8fbf9355646d50

**Comment by johnswekenyi** [comment]
Fixed @Clish254

**Comment by Clish254** [comment]
Works

**Comment by johnswekenyi** [comment]
Wonderful, thank you
