### ISSUE TITLE
[Bug]: Call Service fails when buying airtime using M-Pesa

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#607]
### Description

A << Call service failed >> error is generated when buying Safaricom airtime for your own number using  M-Pesa.your 

### Steps to reproduce

1. Open the Stax app.
2. On the home screen tap Buy Airtime.
3. On the Pay with textbox choose M-PESA and on the Recipient network textbox choose Safaricom
4. On the Amount box enter amount
5. Tap Continue and Tap buy airtime now
6. Enter the pin and wait for the transaction to complete
7. Pay attention to the message on the screen.

### Expected result

Airtime is successfully purchased and the airtime balance returned

### Actual result

A << Call service failed >> error is generated when buying Safaricom airtime for your own number using  M-Pesa.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1VnIWCwhGUqlwZEoqfuFqOLoLwbYCcbK4/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
Fixed @hilderbrandtjohn

**Comment by hilderbrandtjohn** [comment]
Airtime is successfully purchased using M-PESA. 
A new bug in the transactions details screen after successfully purchasing airtime https://github.com/UseHover/Stax/issues/633#issue-1413211050   @johnswekenyi
