### ISSUE TITLE
[Bug]: Purchasing airtime to self not successful

### ISSUE THREAD

**Issue by brysonwaisi** [UseHover/Stax#609]
### Description

**Call service error** is encountered while purchasing airtime from M-PESA to Safaricom

### Steps to reproduce

1. Open the Stax app.
2. On the home screen tap Buy Airtime.
3. On the Pay with textbox choose M-PESA and on the Recipient network textbox choose Safaricom
4. On the Amount box enter amount
5. Tap Continue and Tap buy airtime now
6. Enter your pin and wait for the transaction to go through

### Expected result

Airtime purchase is successful to Safaricom line through M-PESA.

### Actual result

 **Call service failed** error is displayed on the screen

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1E4iBNFBijOmh91POFoMDw6kl4lgnPXux/view?usp=sharing

### Device name

Samsung Galaxy A20s

### Android OS

11
### Is your phone dual SIM or single SIM?

Dual SIM

### Stax device ID or email address

brysonnyamwange@gmail.com

**Comment by johnswekenyi** [comment]
Fixed
