### ISSUE TITLE
[Bug]: Sending money using M-PESA fails

### ISSUE THREAD

**Issue by brysonwaisi** [UseHover/Stax#610]
## Description 
Sending money from M-PESA to another subscriber does not work in the application. The error displayed after completing the operation is Call service failed.

## Steps to reproduce

1. Open the Stax app.
2. On the home screen tap Send money.
3. On the Pay with textbox choose M-PESA and on the Recipient network textbox choose M-PESA
4. Enter contact on the Contact phone number box.
5. On the Amount box enter amount
6. Tap Continue and Tap Send money now
7. Enter the pin and wait for the transaction to complete
8. Pay attention to the message on the screen.

## Expected result
Sending money is successful

## Actual Result

**Call Service error** encountered

## Link to screenshots/screen recordings
[https://drive.google.com/file/d/1E4iBNFBijOmh91POFoMDw6kl4lgnPXux/view?usp=sharing](url)

## Device name
Samsung Galaxy A20s

## Android OS
11

## Is your phone dual SIM or single SIM?
Dual Sim

## Stax device ID or email address
brysonnyamwange@gmail.com

**Comment by johnswekenyi** [comment]
It is fixed @brysonwaisi
