### ISSUE TITLE
[Bug]: Call Service fails when using dial USSD to send money using M-Pesa

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#611]
### Description

A << Call service failed >> error is generated when sending money using M-Pesa using the dial USSD.

### Steps to reproduce

1. Open the Stax app.
2. Tap dial USSD button.
3. On the dial USSD screen,scroll and tap M-PESA.
4. Tap  the safaricom SIM on the choose SIM prompt.
5. Select 1 for Send money and Input recipient's number
6. Input M-PESA pin and Tap Send.
7. Pay attention to the message at the bottom of the screen.

### Expected result

Money is successfully sent to recipient and the M-PESA balance returned

### Actual result

A << Call service failed >> error is generated when sending money using M-Pesa using the dial USSD.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1WlTdzuOz2Gkn587ozBHgH7Zs4UOZJ__w/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
@hilderbrandtjohn this is fixed, please retry and update us. Thank you
