### ISSUE TITLE
[Bug]: App stuck on splash screen

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#612]
### Description

When I try to open the app after it is cleared on the backstack, it gets stuck on the splash screen and doesn't go past there. I have attached a video below.

### Steps to reproduce

1. Open Stax App.
2. Perform a simple activity
3. Leave the app and remove from recent.
4. Open the app again.

### Expected result

The app should open and I should be able to do transactions.

### Actual result

The app gets stuck on the splash screen.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1HwpvZFRaTj7n6dFF4ZwCEQGgyMoA_vkn/view?usp=sharing

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by johnswekenyi** [comment]
@kibettheophilus it looks like your device has either biometric/PIN/pattern configured as first level security. At Stax we have integrated use of these features so you can securely login to the app using your already set security. This is what might have happened for you, you send the app in the background, cleared it from your active apps which then ended the session that has logged in with your security details. That way on coming back you either have to enter the PIN/Patter or biometric. Maybe on your case when that detail was asked, you tapped on the back button which then removes the prompt to use any of those security features and the app will remain on the splash screen as long as you have not logged in. 

To help with the same, please clear again the app from the recent, open and use the security feature set on your phone to open the app again. Let us know how that goes, thank you.

**Comment by johnswekenyi** [comment]
@kibettheophilus please update me if you managed to sort this out.

**Comment by kibettheophilus** [comment]
> @kibettheophilus please update me if you managed to sort this out.

@johnswekenyi It is still persisting, so I still have to clear data every time I want to use the app after it is cleared from the backstack.

**Comment by kibettheophilus** [comment]
> @kibettheophilus it looks like your device has either biometric/PIN/pattern configured as first level security. At Stax we have integrated use of these features so you can securely login to the app using your already set security. This is what might have happened for you, you send the app in the background, cleared it from your active apps which then ended the session that has logged in with your security details. That way on coming back you either have to enter the PIN/Patter or biometric. Maybe on your case when that detail was asked, you tapped on the back button which then removes the prompt to use any of those security features and the app will remain on the splash screen as long as you have not logged in.
> 
> To help with the same, please clear again the app from the recent, open and use the security feature set on your phone to open the app again. Let us know how that goes, thank you.

My phone doesn't use fingerprint(it doesn't support it), but I think this is unique issue -- since it hasn't been reported by anyone else we can close it.
