### ISSUE TITLE
[Bug]: Sending money using M-Pesa fails

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#613]
### Description

Sending money to another person using M-Pesa option is not going out successfully.

### Steps to reproduce

1. Open Stax App
2. Select send money option
3. Use Mpesa as pay option and reciepient
4. Enter phone number, amount and MPesa pin.
5. A transaction will be initiated but will fail with **Call service failed**

### Expected result

Sending money via Mpesashould be successful.

### Actual result

Not able to send money via Mpesa successfully

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1IBmuHJ2kKPFdHjO0AO9_HGjWvuzhru0m/view?usp=sharing

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by mijiga** [comment]
@kibettheophilus can you please try this again

**Comment by kibettheophilus** [comment]
@mijiga this is still persisting on my side.

**Comment by johnswekenyi** [comment]
@kibettheophilus this issue is fixed, please retry and update us.
