### ISSUE TITLE
[Bug]: Wrong Airtime Balance

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#614]
### Description

When I check my airtime balance, it goes successful(I receive SMS from Safaricom) but the balances being displayed on the app are wrong.

### Steps to reproduce

1. Open Stax App
2. Click on SIMS under bottom menu
3. Check balance

### Expected result

Airtime balance to be displayed on the app. 

### Actual result

The app displays my airtime balance as 0.00

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1IbgXgaCvTHEWLuP13GZgvWUaXc_ZE2ob/view?usp=sharing

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by johnswekenyi** [comment]
This is fixed @kibettheophilus
