### ISSUE TITLE
[Bug]: Transaction still pending on Stax even when it is already completed on user side

### ISSUE THREAD

**Issue by FabianMatata** [UseHover/Stax#617]
### Description

Made a transaction of purchasing airtime via Mpesa for Airtel, transaction was successful but experienced a bug in stax updating the transaction status as pending even after it was successfully completed.

### Expected result

Immediate update of the transaction status to successful once its completed successfully.

### Actual result

Transaction pending.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1aKxmQlMbBu666u5Ce03JhSM6Xv8wBa1H/view?usp=sharing

### Device name

Samsung Galaxy A21s 

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Airtel

### Stax device ID or email address

mfabian601@gmail.com

**Comment by johnswekenyi** [comment]
@FabianMatata is this still an issue on your side? please update us

**Comment by FabianMatata** [comment]
No, after updating the app i get expected status updates.

**Comment by johnswekenyi** [comment]
Wonderful, thank you.

**Comment by FabianMatata** [comment]
You're welcome.
