### ISSUE TITLE
[Bug]: Buying airtime using M-Pesa fails

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#619]
### Description

I bought airtime using MPesa but it did not go through successfully.

### Steps to reproduce

1. Open Stax app
2. Select buy airtime option
3. Select pay with Mpesa
4. Recipient as Safaricom and enter the phone number
5. Initiate transaction and check on history.

### Expected result

Airtime is topped up in my account

### Actual result

The request fails with response, **Call service failed**

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1J70L2d--W6mu7p-dl29cZpWLBNGoSysf/view?usp=sharing

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by johnswekenyi** [comment]
@kibettheophilus this has been fixed, please retry and update us. Happy to continue quashing more bugs :)
