### ISSUE TITLE
[Bug]: Logged out user still able to perform transactions

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#620]
### Description

After a user logs out, they can still be able to perform transactions including viewing history or buying airtime.

### Steps to reproduce

1. Open Stax App
2. Click on Settings on the top right
3. Scroll down and click log out, confrim log out
4. Perform any transaction on the app - buy airtime, check history.

### Expected result

- As a user, when a log out I should be taken to a screen where I should be able to login again. 
- I should not be able to check history of the logged out account

### Actual result

I am not taken to the login screen and I am able to check transactions of the logged out account.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1Izfmq4vGVDGG_VCJaRE83mwT-9_OnhO2/view?usp=sharing

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by johnswekenyi** [comment]
@kibettheophilus thank you for this, this is expected and we plan on making product improvements in the future. We will scope your request in line with our product roadmap.
