### ISSUE TITLE
[Bug]: History is lost when cache is cleared

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#621]
### Description

When I clear cache or basically re-install the app, I cannot view the history of the previous transactions I did while logged in.

### Steps to reproduce

1. Open Stax App
2. Perform any transaction
3. Confirm on the history tab that you have atleast one transaction
4. Clear cache(or reinstall if you don't care about device id)
5. Log in to the app using the same account
6. Check on the history tab
7. There won't be any transactions

### Expected result

When I reinstall the app or log in to my account using another device, I should be able to view my previous transaction history

### Actual result

When I log in after clearing cache or reinstall the app, all the previous transactions are not shown on the history tab.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1ItdEggwVO_tZPxSw450dzqSRPgvy8tvN/view?usp=sharing

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by johnswekenyi** [comment]
@kibettheophilus this is the expected behaviour
