### ISSUE TITLE
[Bug]: Only one sim supported at a time

### ISSUE THREAD

**Issue by Fr1x3** [UseHover/Stax#623]
### Description

on the Sims screen, it shows only one sim card is supported. Also, it randomly selects the supported screen if you alternate selection of bottom navigation e.g. from home to sims

### Steps to reproduce

1. Open Stax app
2. On the bottom navigation bar, navigate to sims screen.

### Expected result

Both sim cards to be supported

### Actual result

Only one sim card supported

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1-dXR3RQibFESXCXjOwg9UtFjykBJfzUn/view?usp=sharing  https://drive.google.com/file/d/1-g7iUnzslLkwnxB1YRoBNfJe7cqYk2Om/view?usp=sharing

### Device name

Samsung Ao3

### Android OS

Android 11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

gathufx@gmail.com

**Comment by johnswekenyi** [comment]
@Fr1x3 we are working to fix this, thank you for raising it.

**Comment by johnswekenyi** [comment]
Fixing this issue on a separate ticket, thank you for raising it. I will close this for now.
