### ISSUE TITLE
[Bug]: Failed to update airtime balance

### ISSUE THREAD

**Issue by Fr1x3** [UseHover/Stax#624]
### Description

Having the checked the balance, gives a try again response even thought the ussd code has succeeded. And even after getting a message response on the balance, it still fails to update in the app.Had to wait for a long period to get a successful updated balance. Also clicking on the trying again button doesn't seem to work.

### Steps to reproduce

1. open Stax app
2. select sim option in the bottom navigation
3. choose check balance on the first sim card
4. choose the first simcard 

### Expected result

Balance of the airtime

### Actual result

failed to update airtime balance in the app but got the text message

### Link to screenshots/screen recordings

video from 1.58 to 6.0 https://drive.google.com/file/d/1-g7iUnzslLkwnxB1YRoBNfJe7cqYk2Om/view?usp=sharing

### Device name

Samsung A03

### Android OS

Android 11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

gathufx@gmail.com

**Comment by johnswekenyi** [comment]
@Fr1x3 this should be fixed now. We will publish a new update today
