### ISSUE TITLE
[Bug]: Failed to access Mpesa

### ISSUE THREAD

**Issue by Fr1x3** [UseHover/Stax#625]
### Description

Initial activation of mpesa option to check balance requires acceptance of display over other apps feature. On research, the android 10 Go Os disontinued the feature on one of their update. Thus, couldn't get past the permission acceptance stage.

### Steps to reproduce

1. Open Stax app 
2. Select Mpesa account for the first time
3. on the home screen, check mpesa balance 
4. Redirected to accept app's permission
5. Accepted the first app permission

### Expected result

access mpesa functionalities

### Actual result

Failed to get permission display over other apps

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1-qFn1oKqP30_H_MrSAv_fZi1NBCkp7yA/view?usp=sharing

### Device name

Samsung galaxy a3 core

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

gathufx@gmail.com

**Comment by johnswekenyi** [comment]
@Fr1x3 does this issue still occur?
