### ISSUE TITLE
[Bug]: wrong mpesa balance

### ISSUE THREAD

**Issue by Clish254** [UseHover/Stax#628]
### Description

When I check my mpesa balance the result from stax is wrong. Stax shows zero as my mpesa balance but that's not correct.

### Steps to reproduce

1. Open stax app
2. Select M-pesa in the "Your accounts" list in the homepage
3. Click check balance next to the balance field or click the refresh icon on the right.
4. Compare the balance shown by stax after the request is completed with the balance shown in the m-pesa balance message that you recieve.

### Expected result

The mpesa balance shown by stax should match the balance in the mpesa balance message from safaricom.

### Actual result

The mpesa balance shown by stax does not match the balance in the mpesa balance message from safaricom.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1fJLudUtuaeigO288I5qeD9aK8AmX-ygt/view?usp=sharing

### Device name

Samsung Galaxy S21 5G

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

8d8fbf9355646d50

**Comment by johnswekenyi** [comment]
@Clish254 please check this as I believe we have already sorted out the issue. Let me know if it persists.

**Comment by Clish254** [comment]
> @Clish254 please check this as I believe we have already sorted out the issue. Let me know if it persists.

Sometimes I get the correct balance but today I still got zero at 20:14 EAT

**Comment by johnswekenyi** [comment]
@Clish254 please check if this is still the case on your side

**Comment by johnswekenyi** [comment]
This has been fixed, closing the bug for now. Please feel free to reopen in case the issue persists. @Clish254
