### ISSUE TITLE
[Bug]: Recipient network logo does not change when sending money

### ISSUE THREAD

**Issue by brysonwaisi** [UseHover/Stax#629]
### Description

When sending money to another subscriber, the Telkom logo persists and does not change

### Steps to reproduce

1. Open the Stax app
2. On the home screen select buy airtime
3. On the buy airtime page select Pay with - M-PESA and select Airtel as the recipient network
4. Go back to the home page
5. Select send money
6. On the send money page select Pay with - M-PESA and select M-PESA as the recipient network

### Expected result

The logo of the service provider is correctly displayed when sending money

### Actual result

Telkom Logo persists when sending money

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1ahZD5stImmuAn9aJ6YEdpYaZjXOaaOWj/view?usp=sharing

### Device name

Samsung Galaxy A20s

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

brysonnyamwange@gmail.com

**Comment by brysonwaisi** [comment]
Bug still persits

**Comment by brysonwaisi** [comment]
The logo does not change when switching to another service provider

**Comment by johnswekenyi** [comment]
@brysonwaisi this issue has been fixed, please confirm. Closing the bug for now but feel free to reopen in case you test and still find the issue.
