### ISSUE TITLE
[Bug]: SIM information for one SIM on the SIM screen displays unsupported when two safaricom SIMs are used on dual SIM

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#630]
### Description

 SIM information for  one Safaricom on the SIM screen displays unsupported when two Safaricom SIMs are used in dual SIM mode 

### Steps to reproduce

1. Open the Stax app.
2. Tap the SIM button .
3. Pay attention to the SIM information for both SIM cards on the SIM screen.

### Expected result

Both Safaricom SIMs' information is displayed on different tabs on the SIMs Screen in dual SIM mode

### Actual result

 SIM information for  one Safaricom on the SIM screen displays unsupported when two Safaricom SIMs are used in dual SIM mode

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1Zwcyu03OYXLSW-VEGyBSKyzimqk-VT-A/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
@hilderbrandtjohn we are yet to fix this bug, we will update you as soon as there is a fix for it. Thank you

**Comment by johnswekenyi** [comment]
Closing as this has already been reported @hilderbrandtjohn
