### ISSUE TITLE
[Bug]: Try Again error is displayed on the Transaction Details screen after successfully buying airtime using M-PESA.

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#633]
### Description

Try Again error is displayed on the Transaction Details screen with missing transaction details after successfully buying airtime using M-PESA. 

### Steps to reproduce

1. Open the Stax app.
2. On the home screen tap Buy Airtime.
3. On the Pay with textbox choose M-PESA and on the Recipient network textbox choose Safaricom
4. On the Amount box enter amount
5. Tap Continue and Tap buy airtime now
6. Enter the pin and wait for the transaction to complete
7. Pay attention to the information on the Transaction Details screen.

### Expected result

Transaction details of the Recipient institution, recipient, amount, date, and successful status are displayed on the Transactions Details screen after successfully buying airtime using M-PESA.

### Actual result

Try Again error is displayed on the Transaction Details screen with missing transaction details after successfully buying airtime using M-PESA. 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1_D5gtOk4wmeAJYcH7bJfmZNL78oapzjh/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
@hilderbrandtjohn I believe this is now sorted, let me know if that isa not the case

**Comment by hilderbrandtjohn** [comment]
@johnswekenyi Error is no longer displayed. However, the pending status still persists on the buy airtime and history screens after successfully buying airtime and receiving a confirmation SMS

**Comment by johnswekenyi** [comment]
Will close this for now and continue to track the issue of the SMS delays separately as seen from issue #733
