### ISSUE TITLE
[Bug]: Wrong Mpesa balance

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#636]
### Description

When checking for my Mpesa balance, I got the amount as 0.00 which is not the right amount.

### Steps to reproduce

1. Open Stax app
2. Click on Mpesa under your accounts
3. Click refresh balance--to initiate check balance process
4. Enter Pin
5. The transaction will go successfully but the balance displayed as 0.00

### Expected result

When I check my balance, I expect the right amount to be displayed.

### Actual result

The balance is being displayed as 0.00.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1KmfWp-CFvVYD5ceyneq0fi499b3jU7-m/view?usp=sharing

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by kibettheophilus** [comment]
Still experiencing this

**Comment by johnswekenyi** [comment]
Will close this as it has already been raised @kibettheophilus.
