### ISSUE TITLE
[Bug]: Pending Status persists on the Check Balance screen after checking M-PESA balance.

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#639]
### Description

A Pending Status persists on the Check Balance screen after successfully checking M-PESA and receiving SMS confirmation

### Steps to reproduce

1. Open the Stax app
2. On Home screen tap Check Balance for the M-Pesa account
3. Choose the M-PESA SIM on the choose SIM prompt.
4. Enter the pin
5. Wait for the transaction to complete
6. Pay attention to the message on the Check Balance screen.

### Expected result

A successful status is displayed on the Check Balance screen after successfully checking the M-PESA balance

### Actual result

A Pending Status persists on the Check Balance screen after successfully checking M-PESA and receiving SMS confirmation

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1_OrH4r6U-6W7Cbx3nB9sTeHIabQEpNNb/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
Already reported
