### ISSUE TITLE
[Bug]: Transaction response error

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#640]
### Description

Every time I do a transaction via the app to buy airtime via M-PESA, check balance via M-PESA, send money via M-PESA, and use USSD. I get SMS notification before the app returns any response. When it does after some wait, it shows an error before a success message. an 

### Steps to reproduce

1. Open the Stax app
2. On Home screen tap Check Balance for the M-Pesa account
3. Choose M-PESA SIM on the choose SIM prompt.
4. Enter the pin
5. Wait for the transaction to complete
6. See a successful/error message
7.  See your balance

### Expected result

Success/No enough funds/cancelation or any error messages

### Actual result

1. Pending status persist
2.  Communication error please try again
3. Success message

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1jkhJgNc8ypV06Yw_gxweOQjytOKc57ts/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
@rOluochKe is this still the case at the moment? If its not then I will proceed to close the bug

**Comment by rOluochKe** [comment]
@johnswekenyi all good

**Comment by johnswekenyi** [comment]
Alrighty, closing this then @rOluochKe
