### ISSUE TITLE
[Bug]:  SMS delays

### ISSUE THREAD

**Issue by Purity-E** [UseHover/Stax#644]
### Description

**1. Checking airtime balance ( Safaricom)**
The transaction is successfully completed but there is no confirmation message. The status is shown as pending on the screen that returns after the transaction.

**2. Buy airtime ( Safaricom)**
The transaction is successful but there is no confirmation message. The status is shown as pending on the screen that returns after the transaction.

### Steps to reproduce

**Checking airtime balance**

1. Open stax app
2. Press SIMs option
3. Press check balance on sim1 safaricom

**Buying airtime**

1. Open stax app
2. Press SIMs option
3. Press 'Buy airtime with 5% or more bonus' on sim1 safaricom
4. Choose recipient network safaricom
5. Choose buy airtime for myself
6. Enter amount
7.  press continue
8. press buy airtime now
9. enter mpesa pin

### Expected result

**Checking airtime balance**

I expected the returning screen to show me my airtime balance.

**Buying airtime**

I expected the returning screen to show me my new m-pesa balance after buying the airtime.

### Actual result

**Checking airtime balance**

Instead of getting my airtime balance, what I got was a pending status. The word pending was also shown on the top screen.

**Buying airtime**

Instead of getting my new m-pesa balance after buying the airtime, what I got was a pending status. The word pending was also shown on the top screen.

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1uH2kCl-7K2wnSrq4O43jDlKDgeFR62ms?usp=sharing

### Device name

Redmi 9

### Android OS

10 QP1A.190711.020

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

purityeverniter@gmail.com

**Comment by johnswekenyi** [comment]
@Purity-E closing this for now as it has already been reported and we are working on a fix. 

Next time please be sure to add descriptive titles to your bugs. Thank you
