### ISSUE TITLE
[Bug]: SIM card not detected though it is inserted

### ISSUE THREAD

**Issue by ashioyajotham** [UseHover/Stax#647]
### Description

The airtime purchase is not completed because the app is unable to detect the SIM card

### Steps to reproduce

1. Open Stax app
2. On homescreen, tap the purchase airtime button
3. Select destination network
4. Enter the recipient number
5. Enter the amount
6. Tap "continue"
7. Enter M-PESA pin

### Expected result

A confirmation from Safaricom showing a successful transaction and a similar amount reflecting on my network SIM-card

### Actual result

I receive a "sim card error" message even though sim card is well inserted.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/13DWB8dxR5VdN0yANI4dPBB45WKMUF_3c/view?usp=sharing

### Device name

Alcatel 9003X

### Android OS

6.1

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

victorashioya960@gmail.com

**Comment by ashioyajotham** [comment]
My pleasure

**Comment by johnswekenyi** [comment]
Are you still experiencing this issue @ashioyajotham

**Comment by ashioyajotham** [comment]
No sir.

**Comment by johnswekenyi** [comment]
Closing the issue then.
