### ISSUE TITLE
[Bug]: Need to Reset Permissions in Order to Check Balance

### ISSUE THREAD

**Issue by M69k65y** [UseHover/Stax#652]
### Description

While attempting to check my MPESA balance (first test for the day), I encountered a pop-up requesting accessibility permissions, having previously granted the app these permissions.

### Steps to reproduce

1. Set phone to Do Not Disturb
2. Open Stax app
3. Tap on M-PESA on the Home view
4. Tap on the Refresh icon at the top right of the screen

### Expected result

Having previously granted the app accessibility permissions, the expected result was that the balance check operation would continue without an additional request for permission.

### Actual result

Having triggered the check balance operation, a pop-up appeared requesting accessibility permissions.

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1ykF0YDOaz_aXIOpMXYKs-lkekbrzVNrK?usp=sharing

### Device name

Nokia 7 Plus

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mikey.wanyoike@gmail.com

**Comment by johnswekenyi** [comment]
Thank you @M69k65y we are checking this

**Comment by johnswekenyi** [comment]
Do you still have this issue @M69k65y

**Comment by johnswekenyi** [comment]
@M69k65y this should be fixed now with release 1.18.2
