### ISSUE TITLE
[Bug]: Transactions timing out

### ISSUE THREAD

**Issue by Purity-E** [UseHover/Stax#654]
### Description

None of the transactions went through. They all take quite a long time to transact and end up failing due to connection error.

### Steps to reproduce

**Checking m-pesa balance**
1. Open stax
2. press home
3. tap on m-pesa
4. refresh balance

**check airtime balance(safaricom)**
1. press SIMs
2. on safaricom tab press check balance

**check airtime balance (airtel)**
1. press SIMs
2. on airtel tab press check balance

**buying airtime**
1. press SIMs
2. tap on buy airtime
3. change recipient network to safaricom
4. choose buy airtime for myself
5. enter amount
6. press continue
7. press buy airtime now
8. enter m-pesa pin and confirm

**sending money**
1. go to home page
2. press send money
3.  enter contact number
4. enter amount
5. press continue
6. press send money now
7. enter m-pesa pin

### Expected result

I expect to get a successful transaction with a confirmation message.

### Actual result

I get a failed transaction with message 'We received no response from MPESA. We don't think this transaction worked. Please try again.'

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1jUg6M5vHi4drfSJhOiNGZ5riatLpIqtm?usp=sharing

### Device name

Redmi 9

### Android OS

10 QP1A.190711.020

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

purityeverniter@gmail.com

**Comment by johnswekenyi** [comment]
@Purity-E could you let me know if this is still persisting, I would like to dig dipper to understand what is happening there for you. Sorry about this.

**Comment by davkutalek** [comment]
This is likely specific to this device

**Comment by Purity-E** [comment]
@johnswekenyi the problem is still persisting even after I updated the device.

**Comment by Purity-E** [comment]
> This is likely specific to this device

@davkutalek do you have other users with Redmi devices or am I the only one with Redmi? I'm just curious to know.

**Comment by davkutalek** [comment]
@Purity-E We have had others, but the last one we have tested is quite old at this point. We should be able to fix the issue but our team will have to buy the same/similar device.

**Comment by Purity-E** [comment]
> @Purity-E We have had others, but the last one we have tested is quite old at this point. We should be able to fix the issue but our team will have to buy the same/similar device.

Okay. Though it did work quite well for me on the first day I did the transactions.

**Comment by davkutalek** [comment]
@Purity-E Oh that is helpful info. Can you try restarting the phone and see if it works after?

**Comment by Purity-E** [comment]
> @Purity-E Oh that is helpful info. Can you try restarting the phone and see if it works after?

Okay. I'll give you feedback on how it has gone.

**Comment by Purity-E** [comment]
> @Purity-E Oh that is helpful info. Can you try restarting the phone and see if it works after?

I've restarted my phone and the transactions are going through now, but I have got pending messages for check balance(safaricom) and send money
