### ISSUE TITLE
[Bug]: Transactions don't reflect as completed on the app

### ISSUE THREAD

**Issue by brysonwaisi** [UseHover/Stax#655]
### Description

Transactions are marked as waiting for confirmation on the app
![XRecorder_20102022_151252](https://user-images.githubusercontent.com/39270063/196946895-b3e53089-8832-46a4-975e-cba13334cafb.jpg)

### Steps to reproduce

1. Open the Stax app
2. Tap on any of the transactions to work on
3. Select the required steps for that transaction
4.  Tap on "Continue" or Enter MPESA PIN

### Expected result

The app recognizes the transactions as done

### Actual result

Transactions are still pending even though they have been  successful

### Link to screenshots/screen recordings

https://drive.google.com/file/d/16kW5qj_EnzqcVRCd93WZ1GMPZiyNlwqO/view?usp=sharing

### Device name

Samsung Galaxy A20s

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

brysonnyamwange@gmail.com

**Comment by johnswekenyi** [comment]
@brysonwaisi this has already been reported, will close it and track the first one that was reported. Thank you fo reporting though.
