### ISSUE TITLE
 [Bug]: Check mpesa balance

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#657]
### Description

For checking M-PESA balance, the wait is too long and it shows an error before the actual balance

### Steps to reproduce

1. Open the Stax app
2.  Select account, M-PESA
3. Tap the refresh icon on the right
4. Enter PIN
5. Press CONFIRM button

### Expected result

Success message and a balance

### Actual result

Error then balance message

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1CTTLSC0o_w61BUiG8QOBSwlWOTZW252V/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
Also related to the one you raised, we are resolving on another ticket.
