### ISSUE TITLE
[Bug]: Check Airtime balance

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#658]
### Description

For checking the airtime balance, the wait is too long, shows an error before the actual balance message, and when you click the continue button, the status is pending.

### Steps to reproduce

1. Open the Stax app
2. Tap on the SIMs option
3. Select a sim card
4. Tap the Check balance button

### Expected result

Balance message

### Actual result

Error message and a pending status

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1CTTLSC0o_w61BUiG8QOBSwlWOTZW252V/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
This has been reported before, will close it for now and track as previously reported.
