### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RoyalRoys435** [UseHover/Stax#659]
### Description

when sending airtime to another number even if it succesfully sends the airtime the stax app still shows pending payments even after 24hrs. find the link to the screenshots below
https://drive.google.com/file/d/1ZIbzsl_cGsx4EX1vBTWZKiSZfuS7VUgi/view?usp=sharing

### Steps to reproduce

1. Open stax app
2. Go to buy airtime 
3. Choose mpesa 
4. Buy airtime for any number
5. Check history the pending status changes to complete

### Expected result

I expected the application to show completion of the service like when using other mpesa services in the application
A user can think the process didnt go through because of the pending status not changing

### Actual result

pending status never changes still stays the same

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1ZIbzsl_cGsx4EX1vBTWZKiSZfuS7VUgi/view?usp=sharing

### Device name

cubot

### Android OS

10.1.0

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

58ee3f13f1e19686

**Comment by johnswekenyi** [comment]
Closing this for now as it has been reported before. Will add it to the list.
