### ISSUE TITLE
[Bug]: error unsurported sim

### ISSUE THREAD

**Issue by michaelmuriith** [UseHover/Stax#662]
### Description

One of my sims is labeled unsuported and yet its on the same network

### Steps to reproduce

1.open stax app
2. click on sim tab

### Expected result

both should be supported

### Actual result

unsuported  sim

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1Sh648sHLDrofDDnw8EyYihnIwtwa0GZU/view?usp=sharing

### Android OS

techno pop 5p

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

michaelwanjiru01@gmail.com

**Comment by johnswekenyi** [comment]
This bug has been reported by another person, we have logged it for fixing.
