### ISSUE TITLE
[Bug]: Wrong SIM Card displayed

### ISSUE THREAD

**Issue by ashioyajotham** [UseHover/Stax#667]
### Description

When checking history of transactions, in stead of displaying Safaricom which is the only SIM card available, it shows "MTN" but when I switch to Telkom, it works fine; it displays Telkom network.

### Steps to reproduce

1. Open Stax app
2.  Click "History" tab

### Expected result

The app ought display Safaricom when the Safaricom is inserted 

### Actual result

The app displayed MTN network

### Link to screenshots/screen recordings

https://drive.google.com/file/d/15z4F2QjjmO-I_xipruUpowEoZD-A8LOD/view?usp=sharing

### Device name

Alcatel 9003X

### Android OS

6.1

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

victorashioya960@gmail.com

**Comment by mijiga** [comment]
@ashioyajotham what happens when you tap check balance? Please share video if possible

**Comment by ashioyajotham** [comment]
It shows the MTN network as shown in the screenshot
Best Regards,
Victor (Jotham) Ashioya | LinkedIn
<https://www.linkedin.com/in/ashioyajotham/>

**Comment by mijiga** [comment]
I meant when you press the check balance button in the screenshot

**Comment by ashioyajotham** [comment]
SIM card error.
Best Regards,
Victor (Jotham) Ashioya | LinkedIn
<https://www.linkedin.com/in/ashioyajotham/>

**Comment by mijiga** [comment]
@davkutalek

**Comment by johnswekenyi** [comment]
@ashioyajotham is this still an issue fro you?

**Comment by ashioyajotham** [comment]
Sorry am no longer in the program but last I checked it was
