### ISSUE TITLE
[Bug]: Phone blanks severally while on different apps since app installation

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#668]
I### Description

Since I installed the app, my phone keeps doing this thing like it's turning pages. It goes black for a millisecond and it's like to the left and back. It does so on every app I am on, and there is no specific time period between the actions, sometimes it's many minutes, sometimes seconds.
Check the recording below at the 1.21 mark. 

### Steps to reproduce

1. Open any app
2. It might happen or not. 

### Expected result

No black interruptions on any app

### Actual result

Phone keeps getting these black millisecond breaks on any app I am on. You can't miss it and most times I continue without any thought to it, but on an app like Netflix, the video closes and stops and I have to fire it up again. 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1pwESRTo-vxHt9TElhOKQb6dVcCjUV2h1/view?usp=drivesdk

### Device name

Huawei y5 2019

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

suemnjeri@gmail.com

**Comment by johnswekenyi** [comment]
@suemnjeri please add a title to your bug

**Comment by suemnjeri** [comment]
The same problem persists after app update

**Comment by johnswekenyi** [comment]
@suemnjeri sorry about this, do you still experience this issue?

**Comment by suemnjeri** [comment]
Yes it does. It's like an app refresh, such that the app launches for a millisecond then minimizes itself.  At one time my phone was slow (was on other mem intensive apps), the whole app launched to the screen and didn't close

**Comment by johnswekenyi** [comment]
@suemnjeri this should be resolved when you update the app to the latest release 1.18.2
