### ISSUE TITLE
[Bug]: Check airtime balance wait

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#673]
### Description

Can the wait be made to process faster when communicating to the USSD? 

### Steps to reproduce

1. Open stax app
2. Navigate to the SIMs tab
3. Select your SIM cards, Safaricom
4. Tap the Check balance button on the right

### Expected result

Success or Fail Message

### Actual result

The wait is too long then the error and pending status

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1vbSQgWWSJxuIqh_9gnph8BULewqzWaTy/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
Logged as part of #733
