### ISSUE TITLE
[Bug]: buy airtime wait

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#674]
### Steps to reproduce

1. Open Stax app
2. On home tab
3. Select the buy airtime icon on the top
4. Pay with, Select M-PESA
5. Select recipient, safaricom
6. Buy airtime for, Myself
7. amount
8. Tap the continue button at the button right
9. Confirm Buy airtime now button

### Expected result

Success or fail message

### Actual result

Wait is too long, error and pending status

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1vbSQgWWSJxuIqh_9gnph8BULewqzWaTy/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
Please make sure your bug has the following things clearly submitted @rOluochKe 
- Title
- Description of what the issue is
- Clear Steps to reproduce
- Expected results
- Actual results.

**Comment by johnswekenyi** [comment]
Logged as part of #733
