### ISSUE TITLE
[Bug]: Bank Channel names have the suffix "placeholder"

### ISSUE THREAD

**Issue by mijiga** [UseHover/Stax#675]
### Description

When you add a bank channel to your list of channels, it is added with the suffix "placeholder". For instance COOP Bank as a channel would be added as "COOP Bank placeholder"

### Steps to reproduce

1. Open Stax app
2. On Home Screen tap the Add an account button
3. Select any channel that is a bank e.g COOP Bank, Equity or Bank of Africa
4. Tap continue to add it.

### Expected result

That the channel is added with the same title that the user select in the channel list.

### Actual result

The channel is added with the the suffix "placeholder" and this naming is consistent across most if not all the screens.

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1dqPe12hlO9dSE9kcFtrd7455wkp-gliw

### Device name

Samsung M31s

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

steve@usehover.com

**Comment by johnswekenyi** [comment]
This is now fixed.
