### ISSUE TITLE
[Bug]: Recipient network logo does not update correctly

### ISSUE THREAD

**Issue by ETHreds** [UseHover/Stax#677]
### Description

if i go to the send money tab immediately after coming from buy airtime tab ,the Telkom network logo icon still remains  at the recipient network even though i t indicates mpesa

### Steps to reproduce

1. Open stax app
2. Click on buy airtime
4. Go back to homepage
5. Click on send money

### Expected result

Mpesa/safaricom logo should show in the recipient network box

### Actual result

Telkom logo  shows in the recipient network box 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1DiWIZgH2lnUv-v__yQ5mLcAS-u54yii1/view?usp=sharing

### Device name

Oppo A1k

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mjoejnr@gmail.com

**Comment by johnswekenyi** [comment]
Please add a title to this bug report @ETHreds

**Comment by johnswekenyi** [comment]
Being addressed in #629
