### ISSUE TITLE
[Bug]: Choose SIM prompt is displayed after tapping check balance for one SIM in dual mode

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#685]
### Description

A Choose SIM prompt is displayed on the SIMs screen after taping check balance for one SIM on dual SIM mode.

### Steps to reproduce

1. Open the Stax app.
2. Tap the SIM button.
3. Tap check balance for one  SIM.
4. Pay attention to the pop-up menu on the SIM screen.

### Expected result

Transaction to check the balance for the selected SIM starts after clicking check balance without selecting again through prompt

### Actual result

A Choose SIM prompt is displayed on the SIMs screen after taping check balance for one SIM on dual SIM mode.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1ceBqIsBxLNTaHUSB5IV15kKtki7mvjm-/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
@hilderbrandtjohn we dont think this is a bug

**Comment by hilderbrandtjohn** [comment]
Thank you for the update. Allow me to comment that it is an inconvenience to choose SIM twice and a flaw in the design. I recommend that you consider having the user choose SIM only once on the SIM screen in dual mode. to avoid repetition and addition of steps
