### ISSUE TITLE
[Bug]: No confirmation SMS

### ISSUE THREAD

**Issue by ashioyajotham** [UseHover/Stax#686]
### Description

When checking the airtime balance, the app returns a "still pending" message under history

### Steps to reproduce

1. Open Stax app
2.  Click the check balance

### Expected result

A balance from my network service

### Actual result

"Pending" notification

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1DS-T33rg6-jDD5iA3bmSmqn9raBWWViI/view?usp=sharing

### Device name

Alcatel 9003X

### Android OS

6.1

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

victorashioya960@gmail.com

**Comment by johnswekenyi** [comment]
Related to #733
