### ISSUE TITLE
[Bug]: Mpesa balance displayed as transaction ID

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#687]
### Description

Mpesa balance is being displayed as the transaction ID on the history.

### Steps to reproduce

1. Open Stax app
2. Check balance
3. Check the transaction ID on the history after receiving the message
 

### Expected result

Transaction ID should match the Mpesa transaction ID or should be something unique

### Actual result

The amount which is the Mpesa balance is being displayed as the transaction ID.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1LICxm56RsVfF24ZhUgxcKRFXdL4f7Qpp/view?usp=sharing

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by johnswekenyi** [comment]
@kibettheophilus it is not clear from this description and the attached video what the issue is, please clarify.

**Comment by kibettheophilus** [comment]
@johnswekenyi check on the screenshot below, the transactionId field
![amount_as_id](https://user-images.githubusercontent.com/61080898/198546790-bfaf84fa-59e0-4914-b34b-2c6369ad190a.png)

**Comment by johnswekenyi** [comment]
Thank you, got it now @kibettheophilus

**Comment by johnswekenyi** [comment]
@kibettheophilus please check if you are still experiencing the issue.
