### ISSUE TITLE
[Bug]: Transactions pending for too long

### ISSUE THREAD

**Issue by Clish254** [UseHover/Stax#689]
### Description

Some transactions are staying on the pending page for too long, e.g check mpesa balance and send money. This happens at random times but very often. Here is a transaction that has been pending for more than 14hrs https://drive.google.com/file/d/1kROy7KK2h7xN7wHYMBK8-RWumCcNCrUx/view?usp=sharing.

### Steps to reproduce

1: Open stacks app
2: Perfom any transaction on the homepage e.g check mpesa balance or send money or buy airtime.
3: You will notice that the transaction stays pending on stax sometimes long after receiving a confirmation sms.

### Expected result

Transactions should not be stuck on pending for long after receiving an sms confirmation e.g from m-pesa. 

### Actual result

Transaction still on the pending page on stax after 14+ hours https://drive.google.com/file/d/1kROy7KK2h7xN7wHYMBK8-RWumCcNCrUx/view?usp=sharing

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1kROy7KK2h7xN7wHYMBK8-RWumCcNCrUx/view?usp=sharing

### Device name

Samsung Galaxy S21 5G

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

8d8fbf9355646d50

**Comment by johnswekenyi** [comment]
Related to #733
