### ISSUE TITLE
[Bug]: Airtime balance does not increase despite buying with mpesa

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#690]

**Comment by suemnjeri** [comment]
I have purchased 1 shilling airtime using mpesa twice today, but my airtime balance is still the same. However, my mpesa balance has been deducted.
My mpesa balance is currently zero and I am using the fuliza loan, which has increased by 2 shillings for each subsequent one shilling I bought for airtime.

Video recording link:
https://drive.google.com/file/d/1qr8zCOHNvHXab9eVlbL2sHjnJdv00G1r/view?usp=drivesdk

**Comment by johnswekenyi** [comment]
This was fixed @suemnjeri . Right now if you enter any airtime less than 6 shillings you wont be allowed to proceed with the trxn.
