### ISSUE TITLE
[Bug]: broken integration error

### ISSUE THREAD

**Issue by michaelmuriith** [UseHover/Stax#695]
### Description

when refresh the mpesa service I get a broken integration error

### Steps to reproduce

1. open stax app
2. go to to mpesa tab refresh
3. or open the mpesa and try refreshing the balance 

### Expected result

to get the mpesa balace and update

### Actual result

responds with a broken integration error

### Link to screenshots/screen recordings

https://drive.google.com/file/d/15sb10uUxDMwgvXwNzujGi_b7_4bdF3mY/view?usp=sharing

### Device name

techno pop 5p

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

michaelwanjiru01@gmail.com

**Comment by johnswekenyi** [comment]
Relates to #710
