### ISSUE TITLE
[Bug]: M-PESA failure

### ISSUE THREAD

**Issue by ashioyajotham** [UseHover/Stax#697]
### Description

When trying to send money, I receive "a no response message" then "failed" while a pop-up notification reads "waiting response"

### Steps to reproduce

1. Open Stax
2.  Click send money
3. Enter destination number and similar network
4. Enter amount
5. Enter M-PESA pin

### Expected result

A successful transaction notification

### Actual result

A "failed" transaction notification

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1-XAnjQQ_A6cX36CClDH0U0sVA2EZWmEx/view?usp=sharing

### Device name

Alcatel 9003X

### Android OS

6.10

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

victorashioya960@gmail.com

**Comment by johnswekenyi** [comment]
Relates to #733
