### ISSUE TITLE
[Bug]: Populating name and number in send money

### ISSUE THREAD

**Issue by ETHreds** [UseHover/Stax#698]
### Description

When sending money, When you click on the suggested previous suggestions,the recipients number field is filled with both the name and phone number instead of only the number.I was not able to test if it affects the working of the operation there was errors in the operation

### Steps to reproduce

1. Open Stax app
2. Select send money
3. Click on one of the suggested contacts with a name 

### Expected result

I expect the recipients field to only have  either only the name or phone number of the recipient

### Actual result

The recipient field in send money is filed with the name and phone number of the recipient

### Link to screenshots/screen recordings

https://drive.google.com/file/d/16--ZEVN0Ea4bv-XpVRyle62NTB4TNMA-/view?usp=sharing

### Device name

Oppo A1k

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mjoejnr@gmail.com

**Comment by johnswekenyi** [comment]
@ETHreds this is not a bug.

**Comment by johnswekenyi** [comment]
Let me know if you can test further if it affects the rest of the process
