### ISSUE TITLE
[Bug]: Email addresses shown as contact suggestions in send money

### ISSUE THREAD

**Issue by ETHreds** [UseHover/Stax#699]
### Description

When you are at the send money option,When you tap on the input field of the recipient contact,you first see suggestions of previous transaction contacts that quickly disappear when then  keyboard appears. When the keyboard appears the suggestions then change from mobile numbers to emails

### Steps to reproduce

1. Open Stax app
2. Go to send money
3. Tap on to the recipient contact input field as if you want to input phone number

### Expected result

1. I expect the suggestions based on previous transactions to remain when the device keyboard pop.
2. The keyboard to be only numeric as the on that pops when inputing amount.
3. If the keyboard is to remain the same (apha-numeric) you type a contact name and gets suggestions on the contact you are looking for especially since stax app ask for permission to read the contacts
4. No email suggestions when trying to input contact

### Actual result

Email suggestions when the keyboard comes up when trying to input recipients  phone number

### Link to screenshots/screen recordings

https://drive.google.com/file/d/15rsyuSoCFZ4JWpb6EaICsR1REBzmYLdQ/view?usp=sharing

### Device name

Oppo A1k

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mjoejnr@gmail.com

**Comment by johnswekenyi** [comment]
@ETHreds we dont think this is a bug, I will close it for now unless someone else is able to reproduce.
