### ISSUE TITLE
[Bug]: Unable to check MPESA balance

### ISSUE THREAD

**Issue by ETHreds** [UseHover/Stax#701]
### Description

When trying to update to my current mpesa balance, I get an error saying the service integration is broken

### Steps to reproduce

1. Open Stack app
2. Click on the refresh icon of your mpesa account to view balance

### Expected result

The operation runs and request for your mpesa balance and your account balance is updated

### Actual result

an error stating the service is broken

### Link to screenshots/screen recordings

https://drive.google.com/file/d/15wnkyLAGwdDMiHUK0kbXbl-8Z95z5lu_/view?usp=sharing

### Device name

Oppo A1k

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mjoejnr@gmail.com

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
