### ISSUE TITLE
[Bug]: Unable to buy airtime 

### ISSUE THREAD

**Issue by ETHreds** [UseHover/Stax#702]
### Description

When trying to buy airtime using Mpesa,the transaction doesnt go through and the pay with box turns red with an error message

Ps :Watch video from 0:45

### Steps to reproduce

1. Open Stax app
2. Got to the sims tab
3. click on the buy airtime button
4. Fill  the prompts appropriately
5. 

### Expected result

The transaction operation takes place as Stax supports buying airtime using mpesa and if a error occurs ,the error is indicated

### Actual result

The operations is not perfomed and an error indicating the service is unavailable is shown

### Link to screenshots/screen recordings

https://drive.google.com/file/d/15uVLgMBZJYbNCfQhPsxP_ubQr3lL8Uab/view?usp=sharing

### Device name

Oppo A1k

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mjoejnr@gmail.com

**Comment by johnswekenyi** [comment]
This should now be fixed.
