### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RoyalRoys435** [UseHover/Stax#703]
### Description

I tried buying airtime from safaricom to airtel on the app it says pending but the airtime has already been sent but the recipient hasn;t recieved it yet 

### Steps to reproduce

1. open stax app
2. go to buy airtime
3. input mpesa as the payment option
4. input telkom as the recipient network
5. enter number, amount then click continue and confirm
6. the status remains pending but the money has been sent yet the airtime doesnt reach the recipient on the other network

### Expected result

sttus should change to completed and airtime should succesfully be sent to other network 

### Actual result

sttus remains pending and the airtime doesnt reach the other network

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1sdo2b0QevGWDOZi90vNAjwWUwj9wibEp?usp=sharing

### Device name

cubot

### Android OS

10.1.0

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

58ee3f13f1e19686

**Comment by johnswekenyi** [comment]
@RoyalRoys435 is this still an issue?
