### ISSUE TITLE
[Bug]: Waiting too long to get M-PESA balance

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#704]
### Description

When checking for your M-PESA balance, the wait is too long (between 1 - 2 mins), can it be made to process faster than the SMS?

### Steps to reproduce

1. Open Stax app
2. On the home screen
3. Tap add an account icon
4. In the search field, add an account, M-PESA
5. Select country, Kenya
6. Back to the home screen, click the refresh icon on the Your accounts section
7. Put in your pin
8. Confirm by pressing the confirm button
9. Wait for your balance message

### Expected result

My M-PESA balance statement

### Actual result

M-PESA balance statement but after a long wait 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1YloppBrFxkgZBGSM-RiKq_sXMPQnCjJe/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
@rOluochKe this should be fixed now, please check and revert when you can. Thank you

**Comment by rOluochKe** [comment]
@johnswekenyi all good now

**Comment by johnswekenyi** [comment]
@rOluochKe this should be fixed now with release 1.18.2
