### ISSUE TITLE
[Bug]: Airtime does not increase despite deducting from mpesa when on fuliza

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#705]
### Description

When I buy airtime with the app from mpesa with fuliza, it shows a confirmation message successful, that it has been purchased for account stax, but my airtime never increases in balance. So where does this money go? 

### Steps to reproduce

1. Open stax app
2. Buy airtime
3. Enter safaricom, amount 2 shillings and continue.
4. Enter mpesa pin
5. Submit

### Expected result

The airtime is purchased from mpesa, I enter a confirmation whether to accept fuliza or not, and the message returned is for account <my_number>. 

### Actual result

Once I enter my pin and submit, the app goes ahead and buys the airtime for me and even accepts to use fuliza. The message from mpesa is then returned saying airtime has been bought for account stax, not my number 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1rI6TSGutMSsX1ZHYAR-OoMn6JzfblkE_/view?usp=drivesdk 

### Device name

Huawei y5 2019

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

suemnjeri@gmail.com

**Comment by johnswekenyi** [comment]
Related to #690
