### ISSUE TITLE
[Bug]: Unable to check bank balance

### ISSUE THREAD

**Issue by brysonwaisi** [UseHover/Stax#707]
### Description

No response from Bank while fetching accounts

### Steps to reproduce

1. Open the Stax app
2. On the home screen select the appropriate account (Bank)
3. Click on the check balance refresh icon
4. Select the sim to complete the transaction 
5. Wait for the transaction to complete

### Expected result

The bank balance is displayed on the balance screen

### Actual result

Pending status stalls or a fetching account error (No response from Bank) is displayed.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/10yb2GYZl-l27NwPCi8inNRIVEMYqAP-D/view?usp=sharing

### Device name

Samsung Galaxy A20s

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

brysonnyamwange@gmail.com

**Comment by johnswekenyi** [comment]
Merging this with #708
