### ISSUE TITLE
[Bug]: Purchasing airtime for self from Bank fails

### ISSUE THREAD

**Issue by brysonwaisi** [UseHover/Stax#708]
### Description

Purchasing airtime from Bank to M-PESA fails to go through 

### Steps to reproduce

1. Open the Stax app
2. On the home screen select Buy airtime
3. Click on the check balance refresh icon
4. Choose the bank as the sender and the mobile network as the recipient
5. Input the recipient's phone number and amount then click on continue
6. Connect the account with the Bank
7. Select the sim to complete the transaction 
8. Wait for the transaction to complete

### Expected result

The airtime purchase is successful and the account is credited.

### Actual result

Pending status stalls while purchasing airtime.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/10yb2GYZl-l27NwPCi8inNRIVEMYqAP-D/view?usp=sharing

### Device name

Samsung Galaxy A20s

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

brysonnyamwange@gmail.com

**Comment by johnswekenyi** [comment]
@brysonwaisi this should be fixed now with release 1.18.2
