### ISSUE TITLE
[Bug]: Broken Service Integration error is displayed while checking balance for Equity bank

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#710]
### Description

A broken service integration error is displayed on the home screen after tapping the check balance icon for the Equity account.

### Steps to reproduce

1. Open the Stax app
2. Tap the check balance icon for the Equity account.
3. Pay attention to the message at the bottom of the homescreen.home screen

### Expected result

The equity account balance is successfully returned after tapping the check balance icon.

### Actual result

A broken service integration error is displayed on the home screen after tapping the check balance icon for the Equity account.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1fLmaZK0CYgYlkBptJPvDBW5VKgs1rqZZ/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
