### ISSUE TITLE
[Bug]: A Fix errors error message is displayed on the Send Money Screen After tapping the Continue button.

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#711]
### Description

A Fix errors error message is displayed on the Send Money Screen After tapping the Continue button.

### Steps to reproduce

1. Open the Stax app
2. Tap send money icon on the home screen
3. Select Pay With Equity on the send money screen
4. Select Recipient Network as M-PESA
5. Enter Contact Phone Number
6. Enter Amount in the Amount text box
7. Tap on the Account name box to enter text
8. Tap continue and pay attention to the error message displayed and the uneditable Account name box.

### Expected result

The transaction to send money is completed successfully after tapping the continue button on the Send Money screen.

### Actual result

A Fix errors error message is displayed on the Send Money Screen After tapping the Continue button.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1fMZfJW2HbiGLuIpLxsLu0t4XnDWwkFnA/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
Thank you @hilderbrandtjohn this is noted and logged for fixing

**Comment by johnswekenyi** [comment]
@hilderbrandtjohn this should be fixed now with release 1.18.2
