### ISSUE TITLE
[Bug]: Pending Status Persists indefinitely after buying airtime using Equity account

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#713]
### Description

 Pending Status Persists indefinitely on the Buy airtime screen after buying airtime using the Equity account

### Steps to reproduce

1. Open the Stax app
2. Tap the Buy Airtime icon
3. Select Pay with Equity
4. Select the recipient network as Safaricom
5. Enter the Contact phone number and Amount
7. Tap Buy Airtime Now and Choose SIM 1
8. Enter the Equity bank pin and wait for the transaction to complete

### Expected result

Transaction to purchase Safaricom airtime is successfully completed after buying airtime using the Equity account.

### Actual result

 Pending Status Persists indefinitely on the Buy airtime screen after buying airtime using the Equity account

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1fKAP0S2f1LV71Xv_FV4K-IhZrmpVLRci/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
Merging with #715
