### ISSUE TITLE
No Notification Message From Equity Bank and Safaricom after buying airtime

### ISSUE THREAD

**Issue by Sally-N** [UseHover/Stax#716]
### Description

A  message from Equity Bank on account credit and a message from Safaricom on receipt of new and increased current airtime balance are not received.

### Steps to reproduce

1. Open the Stax app.
2. On the home screen click on the Buy airtime icon.
3. On the “pay with” input field, select Equity bank.
4. On the “recipient network” input field, select Safaricom.
5. On the “Contact phone number” input field, enter your phone number
6. On the “Amount” input field, enter the amount.
7. Wait for the buy airtime transaction to complete.

### Expected result

Two notification messages from Equity Bank and Safaricom

### Actual result

Confirmation messages alerting the buying of airtime are not received.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1LM4A5YpecoHx1FD8zGtlysb2CFSd_JI8/view?usp=sharing

### Device name

Samsung Galaxy A22

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

snzungula@gmail.com

**Comment by johnswekenyi** [comment]
Merging with #715
