### ISSUE TITLE
[Bug]: Equity bank account fails to prompt PIN when checking balance

### ISSUE THREAD

**Issue by jnjerin** [UseHover/Stax#719]
### Description

Equity account fails to bring the prompt screen to input the PIN and instead proceeds to USSD communication when checking balance.

### Steps to reproduce

1. Open Stax app.
2. On home screen click on equity account.
3. Click on the Balance refresh button.
4. Choose either of the SIM options.

### Expected result

A screen to input PIN shows up after choosing the SIM.

### Actual result

Initiates USSD service  communication, then shows successful status with no results of balance.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1o3p5i1pj55YNW4bIiYxRVCb1l9W7uioJ/view?usp=sharing

### Device name

Redmi Note 9S

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

11f9c800e06a3cea

**Comment by johnswekenyi** [comment]
Merging with #715
