### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kelvin-Wepo** [UseHover/Stax#720]
### Description

On the home screen after adding a bank account,despite having a stable internet connection the app is not linked instead i get an error message listed below.

 "Unknown error,see ussd log to find out what went wrong.please try again" 

### Steps to reproduce

1.open stax app
2.on home screen tap add account
3.Enter Pin
4.Wait for transaction to complete

### Expected result

When I add my account it should be approved and automatically direct me to the homepage of my bank app

### Actual result

 Despite having strong internet connection,the account is not linked instead i get this error "Unknown error,see ussd log to find out what went wrong.please try again" and when i check the ussd there is nothing to display.

### Link to screenshots/screen recordings
https://drive.google.com/drive/my-drive

### Device name

Huawei Y5 prime

### Android OS

8.1.0

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

kelvinwepo7710@gmail.com

**Comment by johnswekenyi** [comment]
@Kelvin-Wepo please add a correct link to the screenshot/recording, what you added is a google form. Also add a title to the bug
