### ISSUE TITLE
[Bug]: Unable to Add NCBA Bank Details

### ISSUE THREAD

**Issue by M69k65y** [UseHover/Stax#721]
### Description

An error message is displayed when attempting to add NCBA account details to the Stax app.

### Steps to reproduce

1. Open Stax ap
2. On the Home screen, click on NCBA
3. Fill the Account number and nickname fields and save
4. Tap on Dial *488#
5. Choose SIM card to use to dial

### Expected result

To add NCBA bank details to the app.

### Actual result

Attempting to add bank account details by dialling *488# yields different messages on Safaricom and Airtel:
Safaricom: Sorry you are not registered with NCBA Bank.
Airtel: Sorry, there was a problem processing your request.

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1ykF0YDOaz_aXIOpMXYKs-lkekbrzVNrK?usp=sharing

### Device name

Nokia 7 Plus

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mikey.wanyoike@gmail.com

**Comment by davkutalek** [comment]
Have you definitely registered your phone number with your bank account and enabled mobile banking?

If so then this could be a due to the way NIC and CBA migrated when they merged into NCBA. Could you please try dialing *654# in your phone app and see if that works?

**Comment by johnswekenyi** [comment]
Merging with #715
