### ISSUE TITLE
[Bug]: Equitel stax intergration transactions not  working

### ISSUE THREAD

**Issue by Murithijoshua** [UseHover/Stax#724]
### Description

checking account balance after adding equity account not working

### Steps to reproduce

1. open stax app
2. Select EQuity Bank placeholder
3. select your balace

### Expected result

1. open stax app
2. Select EQuity Bank placeholder
3. select your balace
4. Enter PIN
5. get balance via sms

### Actual result

We received no response from Equity bank. We don't think this transaction went through. try again

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1UzVUSUUSX_pXUM2T7_mgH50PxjQiedCx/view?usp=sharing

### Device name

Gionee s8s

### Android OS

9.0

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Equitel

### Stax device ID or email address

c074faae6ae398cd

**Comment by johnswekenyi** [comment]
@Murithijoshua is Equitel and Equity check balance the same thing? Looks like you are using your Airtel line to check balance, is this the line registered on your Equity account?

And did you mean Equity check balance or Equitel check balance on the title of this bug?

**Comment by Murithijoshua** [comment]
* Equitel is equity's simcard, we use equitel to check account balance as well as perform money transactions. 
* one can check your Equity account balance using equitel, it same thing. instead of walking to Equity bank one can use equitel.
* For simcard I asked for help on slack [here](https://staxhacktober.slack.com/archives/C044ZLJRR9B/p1666857741257899) no one responded

**Comment by johnswekenyi** [comment]
Merging with #715
