### ISSUE TITLE
[Bug]: Connection to NCBA KE Failed

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#725]
### Description

Checking the balance from the Stax app for NCBA KE bank failed.

### Steps to reproduce

1.  Open the Stax app
2.  On the home screen
3.  Your accounts section
4.  Select NCBA Bank
5.  Tap the refresh icon 
6.  Enter your PIN
7.  Press Confirm button
8.  Wait for the message

### Expected result

Success and balance statement

### Actual result

Failed. 
Sorry, you are not registered with NCBA Bank. Please visit your nearest branch for registration or contact ... or email...

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1R_G8ykWSZ_FrIy0rchhI3YRlk1_ZTz2F/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
@rOluochKe are you an account holder at NCBA? Usually this error will be shown if you are using a number that is not registered on Mobile banking even if you are an account holder. Please check that and let us know.

**Comment by johnswekenyi** [comment]
Merging with #715
