### ISSUE TITLE
[Bug]: Coop Bank account connected but can't enquire balance, integration is broken

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#726]
### Description

I was able to connect stax to my cooperative bank account and the 2 accounts associated with the account now show up on the menu for accounts. However, when I try to request the balance, a pop message shows up that 'sorry, service integration is broken'. 

### Steps to reproduce

1.open the stax app
2. Navigate to the bottom of the main screen and click on the coop bank account.
3. At the top of this screen, click on the refresh button that refreshes and returns the balance.
4. Nothing happens, just the pop up indicating that service integration is broken. 

### Expected result

Since I have already connected stax with my cooperative bank account number, and the ussd option *667# works, the app should return the balance. 

### Actual result

When i request the bank balance through the stax app, I get a pop up, 'sorry, service integration is broken' 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1rhInCsWSm_GdREWUqG2DWVOcj9XZn3LF/view?usp=drivesdk

### Device name

Huawei y5 2019

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

suemnjeri@gmail.com

**Comment by suemnjeri** [comment]
Same issue persists, therefore cannot buy airtime or send to mpesa from the bank account.

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
