### ISSUE TITLE
[Bug]: A "Failed" error message is displayed after clicking the "Refresh your balance" link

### ISSUE THREAD

**Issue by NinaWendy** [UseHover/Stax#727]
### Description

A "Failed" error message is displayed after clicking the "Refresh your balance" link. This occurs after entering the account number for COOP Bank and trying to connect with the bank.

### Steps to reproduce

1. Open the Stax app
2. On the home screen tap on the add account icon
3. Select the COOP Bank KE option in the list
4. Add your account number in the input text
5. Click on the "Refresh your balance" icon

### Expected result

The application successfully connects to the bank and the balance is clearly displayed.

### Actual result

An error message is displayed and the account balance is not shown

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1oa7Vs0RxXtq3Fu-Teo5aZ72NZduZ0DI9/view?usp=sharing

### Device name

Xiaomi Redmi Note 11

### Android OS

11.0.0

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

16ae8b92f7f2f029

**Comment by johnswekenyi** [comment]
@NinaWendy this should be fixed now with release 1.18.2
