### ISSUE TITLE
[Bug]: Pending status persists on check balance after successfully querying balance.

### ISSUE THREAD

**Issue by Abbiechebet** [UseHover/Stax#728]
### Description

A pending status persists on the Check Balance after successfully querying balance and receiving confirmation SMS.

### Steps to reproduce

1. Open Stax app.
2. Tap the SMS button.
3. On the SMS screen tap check balance for Safaricom SIM
4. wait for the transaction to complete.

### Expected result

Airtime balance and a successful status are displayed on the Check Balance screen.

### Actual result

A pending status persists on the Check Balance screen after successfully querying balance and receiving confirmation SMS.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1N_xfJvm3MoJ_OR_simZTHo5oixm0MPYS/view?usp=sharing

### Device name

TECNO LA6

### Android OS

7.0

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

abigaelchebet85@gmail.com

**Comment by johnswekenyi** [comment]
Reported in #733
