### ISSUE TITLE
[Bug]: mpesa balance delayed until the next mpesa stax operation

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#729]
### Description

 A request for mpesa balance the first time I open the app for the day does not show the balance, despite receiving a message from mpesa with the balance. Then 10 minutes later when I attempt to buy airtime through mpesa, the balance finally updates

### Steps to reproduce

1. Open the stax app
2. Before any other transaction, click on the reload button next to the mpesa account to get the balance.
3. Enter mpesa pin
4. Click continue
5. Wait for the mpesa balance 

### Expected result

Mpesa balance is updated immediately on the app after balance enquiry. 

### Actual result

Mpesa balance is not updated even after 10 minutes. Only after I perform another mpesa transaction such as buy airtime does the balance update. 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1s1Mf_9tdCFNU85L1-JxDtlsb0lTUJuov/view?usp=drivesdk

### Device name

Huawei y5 2019

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

suemnjeri@gmail.com

**Comment by johnswekenyi** [comment]
Reported in #733
