### ISSUE TITLE
[Bug]: Airtime balance for safaricom fails 'waiting for safaricom message..'

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#730]
### Description

Airtime balance not update despite requesting it severally

### Steps to reproduce

1. Open stax app
2. Navigate to Sim tab
3. Check balance
4. Wait for update

### Expected result

Safaricom airtime balance should update immediately on the app after requesting. 

### Actual result

Airtime balance not updated. Status shows 'waiting for safaricom message' 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1s2jbNajg4AM7pnlQs4Z_uSwk5frv2XNo/view?usp=drivesdk

### Device name

Huawei y5 2019

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

suemnjeri@gmail.com

**Comment by johnswekenyi** [comment]
Relates to #733
