### ISSUE TITLE
[Bug]: Pending status persists when sending money from Mpesa to KCB bank

### ISSUE THREAD

**Issue by larrymiami** [UseHover/Stax#731]
### Description

Pending status persists when sending money from Mpesa to KCB bank after the transaction message is received.

### Steps to reproduce

1. Open the Stax app.
2. On the home screen, click on the send money icon.
3. On the “pay with” input field, select Mpesa.
4. On the “recipient network” input field, select KCB bank.
5. On the “contact account number” input, enter your account number.
6. On the “amount” input, enter the desired amount and click on the continue button.
7. On the “send money”  page press the send money now button and enter your Mpesa pin.
8. Pay attention to the transaction details page.

### Expected result

A confirmation message is received and transaction details are displayed successfully on the screen.

### Actual result

The pending status persists on the transaction page.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/106x7Af_0u6_6JGdeIjWCfNFbQgGSBHnk/view?usp=sharing

### Device name

Nokia 3.2

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

ae3a4fb4d6502412

**Comment by johnswekenyi** [comment]
Relates to #739
