### ISSUE TITLE
[Bug]: Pending status persists when checking the Mpesa balance

### ISSUE THREAD

**Issue by larrymiami** [UseHover/Stax#732]
### Description

Pending status persists when checking the Mpesa balance after successful topup

### Steps to reproduce

1. Open the Stax app.
2. Click on the reload icon next to your Mpesa account.
3. Enter the pin.
4. Pay attention to the transaction details page.

### Expected result

A confirmation message is received and transaction details are displayed successfully on the screen.

### Actual result

The pending status persists on the transaction page.

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1R41SYrnGxkl5Q6dZ-7RThHgVVZSQsxYL?usp=sharing 

### Device name

Nokia 3.2

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

ae3a4fb4d6502412

**Comment by johnswekenyi** [comment]
Closing this as is is related to #733 @larrymiami
