### ISSUE TITLE
[Bug]: Mpesa balance has pending status besides successful balance query.

### ISSUE THREAD

**Issue by LOVELYN15** [UseHover/Stax#734]
### Description

Mpesa balance has pending status besides successful balance query. 

### Steps to reproduce

Open stax app
Dial home screen 
Tap the Mpesa account on your accounts
Tap the right side of the balance 
Enter Mpesa pin
Confirm

If it generates USSD
Enter no. 7
Enter no. 1
Enter PIN
Enter no. 1 

### Expected result

A message should be sent and the balance status should be updated on the app.

### Actual result

Pending balance status on the app despite message being generated successfully.
 

### Link to screenshots/screen recordings

https://drive.google.com/drive/u/0/my-drive

### Device name

OPPO F3 CPH1608

### Android OS

6

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

f61f732fbdc73530

**Comment by johnswekenyi** [comment]
This is logged and we will prioritise

**Comment by johnswekenyi** [comment]
Relates to #738
