### ISSUE TITLE
Delay in communicating with USSD service while buying airtime

### ISSUE THREAD

**Issue by LOVELYN15** [UseHover/Stax#735]
### Description

Delay in communicating with USSD service while buying airtime

### Steps to reproduce

1. Open Stax app
2. Click Home page.
3. Tap Buy airtime
4. Choose Mpesa under the pay with section
5. Click the network you would like to buy airtime to under the Recipient network
6. Choose who you'd like to buy airtime for
7. If for self then enter amount 
8. Click done 
9. Click Buy airtime now
10. Enter Pin
11. Confirm

USSD Service
1. Enter no. 3
2. Enter no. 1
3. Enter no. 1
4. Enter amount
5. Enter PIN

### Expected result

Fast loading process of the USSD service while buying airtime.

### Actual result

Time lag while communicating with USSD service

### Link to screenshots/screen recordings

https://drive.google.com/file/d/16d35qzLK8NuWfaselnkzFqqoAI6I9mCJ/view?usp=sharing

### Device name

OPPO F3 CPH1608

### Android OS

6

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

f61f732fbdc73530

**Comment by johnswekenyi** [comment]
@LOVELYN15 please provide a correct link to the issue

**Comment by LOVELYN15** [comment]
Hello John, I have provided the correct link to issue right now.
