### ISSUE TITLE
[Bug]: Wrong SIM Card detection

### ISSUE THREAD

**Issue by ashioyajotham** [UseHover/Stax#736]
### Description

When I check balance, it indicates two networks; Safaricom and MTN yet my phone is a single SIM 

### Steps to reproduce

1. Open Stax
2. Under SIMs tap check balance

### Expected result

One SIM Card displayed

### Actual result

Two SIM Cards with one not even available in Kenya

### Link to screenshots/screen recordings

https://drive.google.com/file/d/105_8iJ0-QqBOWJHydfnSNrkhacOQf_QU/view?usp=sharing

### Device name

Alcatel 9003X

### Android OS

6.1

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

victorashioya960@gmail.com

**Comment by johnswekenyi** [comment]
Merging this on #667
