### ISSUE TITLE
[Bug]: Pending status persists while transacting money to COOP Bank account.

### ISSUE THREAD

**Issue by LOVELYN15** [UseHover/Stax#737]
### Description

Pending status persists while transacting money to COOP Bank account.

### Steps to reproduce

1. Open Stax app
2. On homepage click send money
3. Click Mpesa on Pay with
4. Click Recipient Network (COOP Bank)
5. Enter account number 
6. Enter amount
7. Click continue
8. Click send money
9. Enter Mpesa Pin

### Expected result

Successful transaction of money to the entered bank account with an Mpesa message confirming the same.

### Actual result

Failed transaction with a message stating "We received no response from MPESA. We don't think this transaction worked. Please try again".

### Link to screenshots/screen recordings

https://drive.google.com/drive/u/0/my-drive

### Device name

OPPO F3 CPH1608

### Android OS

6

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

f61f732fbdc73530

**Comment by johnswekenyi** [comment]
Relates to #739
