### ISSUE TITLE
[Bug]: M-PESA Send Money to Bank Transaction Status Stuck on Pending

### ISSUE THREAD

**Issue by M69k65y** [UseHover/Stax#739]
### Description

The status of the MPESA transaction is not updated on the transaction status screen when attempting to send money to an NCBA bank account.

### Steps to reproduce

1. Open Stax app
2. On the Home screen, tap on Send Money
3. Select NCBA Bank as the Recipient network
4. Enter account number
5. Enter amount
6. Tap on Continue
7. Tap on Send money now

### Expected result

The transaction status screen should indicate whether the transaction was successful or not.

### Actual result

The transaction status screen displays the message, "The USSD session is complete, but we have not received a confirmation SMS yet." This is despite receiving an M-PESA transaction message and a message from NCBA indicating that the transaction was successful.

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1ykF0YDOaz_aXIOpMXYKs-lkekbrzVNrK?usp=sharing

### Device name

Nokia 7 Plus

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mikey.wanyoike@gmail.com

**Comment by johnswekenyi** [comment]
@M69k65y we have logged this issue for fixing.
