### ISSUE TITLE
[Bug]: Stax launching itself despite one exiting the app

### ISSUE THREAD

**Issue by Mally13** [UseHover/Stax#741]
### Description

I have allowed the permissions, now even when I press the back button to leave or even close its background activities. It still finds a way to open itself up. I will be on another app say slack and then it's like it tries to overthrow the other app to become active and I still find it under recent tasks despite closing it multiple times.

### Steps to reproduce

1. Open the Stax app
2. Exit the Stax app by pressing the back button
3. Click on the Recent Tasks button.
4. Close all recent tasks 
5. Open another app, say slack. While using slack for some time you might notice a black flicker.
6. Click the Recent Tasks Button. You will notice Stax there despite having closed it a while ago.

### Expected result

I expected that when I exited the app by pressing the back button or clearing all recent tasks all Stax activities would be destroyed. And that the Stax app wouldn't start itself again without me opening it.  

### Actual result

I exited the Stax app by pressing the back button. I even went to check if it appeared in my phone's recent tasks, but it was still there.
I closed all my recent tasks including Stax. A minute later the screen flickers, like the app was trying to open but crashed. I went to the recent tasks again and Stax had launched itself in the background. 

When I clicked on the Stax task. it couldn't open the app for me to see it on the screen.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1Ti524K6aP4Cm0UVuYzeEKrbBeu181IOK/view?usp=drivesdk

### Device name

Oppo A53

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mallymutuku13@gmail.com

**Comment by johnswekenyi** [comment]
@Mally13 we have logged this and we will prioritise for fixing

**Comment by johnswekenyi** [comment]
@Mally13 this has been fixed and you should be okay with the new release that comes out early next week. Please do let us know if this happens again next week when you update to the new app

**Comment by johnswekenyi** [comment]
@Mally13 we have a new release that is being rolled out gradually with the fix.
