### ISSUE TITLE
[Bug]: Failed Status persists on the Move money screen after successfully sending money.

### ISSUE THREAD

**Issue by Abbiechebet** [UseHover/Stax#744]
### Description

Failed Status persists on the move money screen after successfully sending money and waiting for confirmation.

### Steps to reproduce

1. Open Stax App.
2. Tap the home button.
3. On the home screen tap Send Money icon.
4. Choose bank to pay with.
5. Choose Recipient Network.
6. Send to Someone else or Myself.
7. Enter amount
8. Enter Pin and wait for confirmation.

### Expected result

Amount sent and a successfully status on Move Money screen.

### Actual result

Failed Status persists on the Move money screen after successfully sending money and a redirecting message to use USSD.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1O3ZKsLCiPZTKSVrDOCEJnkMKIHmXeRoz/view?usp=sharing

### Device name

TECNO LA6

### Android OS

7.0

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

abigaelchebet85@gmail.com

**Comment by mijiga** [comment]
@johnswekenyi do you have access to the video? Im still waiting for access from them

**Comment by mijiga** [comment]
@Abbiechebet please clarify. Is what you're saying that the transaction went through and the intended recipient received the amount but the transaction status in Stax is marked as failed? Or?

**Comment by Abbiechebet** [comment]
@mijiga The transaction didn't go through. The intended recipient did not receive the amount.
