### ISSUE TITLE
[Bug]: Accessibility button keeps on turning off 

### ISSUE THREAD

**Issue by Mogakamo** [UseHover/Stax#749]
### Description

My accesssibility feature is having problems in the sense that I get to open it every time I open the application I have to turn on this setting and when I put it on from the settings it says the service is malfunctioning. As a result I am not able to turn the accessibility feature for the application.

### Steps to reproduce

1. Open Stax app
2. Go to the settings option
3. Turn the accessibility option
4. Takes you to the settings of the app
5. Turn the accessibility feature on 
6. Go back to stax app again
7. The accessibility feature is off again

### Expected result

The accessibility option to be on so that I can do the transactions.

### Device name

Itel A58, itel A661W

### Android OS

11.0.0

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

mogaka.amo254@gmail.com

**Comment by johnswekenyi** [comment]
@Mogakamo this is more a device issue and there is so little we can do to control how that works. I will close this for now.
