### ISSUE TITLE
[Bug]: Pending Status while sending money from KBC Bank to Mpesa

### ISSUE THREAD

**Issue by LOVELYN15** [UseHover/Stax#755]
### Description

Pening status while sending money to Mpesa from KCB Bank account. 

### Steps to reproduce

1. Open Stax
2. On the home page tap send money
3. Click pay with 
4. Choose KCB Mobile Banking
5. Click recipient network
6. Choose Mpesa
7. Choose to myself
8. Enter amount
9. Click continue

### Expected result

A successful transaction with return message from both mpesa and kcb bank indicating the same.

### Actual result

Pending status with "we did not detect a confirmation message" displayed on the fetching accounts screen.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/17dbih0-DTOpgLCUPEPa64vur3z2KqbGG/view?usp=sharing

### Device name

OPPO F3 CPH1608

### Android OS

6

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

f61f732fbdc73530

**Comment by johnswekenyi** [comment]
Relates to #733

**Comment by johnswekenyi** [comment]
Relates to #733
