### ISSUE TITLE
[Bug]: Account does not connect to the app

### ISSUE THREAD

**Issue by Kelvin-Wepo** [UseHover/Stax#761]
### Description

When adding a bank account i sometimes get no account found or a message stating that "waiting for KCB bank confirmation" and there after my Bank account is not linked. I can access my bank account through official bank account app

### Steps to reproduce

1.Open stax app
2.On the home screen select add account
3.click on Bank of the choice and press continue

### Expected result

The bank should be linked to my account after clicking on link account button

### Actual result

Bank account is not linked to my app and instead i get  no account message.

### Link to screenshots/screen recordings

https://drive.google.com/drive/my-drive

### Device name

Huawei Y5 prime

### Android OS

8.1.0

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

kelvinwepo7710@gmail.com

**Comment by johnswekenyi** [comment]
@Kelvin-Wepo your description is not quite clear, please refine it for my understanding. You also need to attach a video recording, you only added a link to your drive

> When adding a bank account i sometimes get no account found or a message stating that "waiting for KCB bank confirmation" and there after my Bank account is not linked. I can access my bank account through official bank account app
