### ISSUE TITLE
[Bug]: Failed to buy airtime COOP Bank

### ISSUE THREAD

**Issue by MwitaBrian** [UseHover/Stax#762]
### Description

On tapping the refresh balance icon, a pop-up saying "Sorry, this service integration is broken" appears.

### Steps to reproduce

1. Open Stax app.
2. On homescreen tap on the refresh balance icon for the linked bank account. 
3. Watch for a pop-up "Sorry, this service integration is broken".

### Expected result

Prompt to enter PIN and successfully buy airtime using bank account. 

### Actual result

A pop-up saying "Sorry, this service integration is broken" appears.

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1PgtJdLm3_ksdy4hHWis7Pod1mR6B2_HP

### Device name

Samsung Galaxy A50

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

76f877283734ee49

**Comment by johnswekenyi** [comment]
@MwitaBrian are you still experiencing this issue?

**Comment by MwitaBrian** [comment]
> @MwitaBrian are you still experiencing this issue?

Yes I am. 
Though the COOP bank placeholder option works but only as far as fetching accounts. No transactions can be performed.

**Comment by MwitaBrian** [comment]
Encountered the same bug today

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
