### ISSUE TITLE
Account name issue

### ISSUE THREAD

**Issue by Purity-E** [UseHover/Stax#770]
### Description

When I want to send money from the bank to my m-pesa account, I am unable to enter my account name or recipient name. 

### Steps to reproduce

1. Open stax
2. Go to send money
3. On pay with enter equity bank all accounts
4. On recipient network enter m-pesa
5. Enter account number
6. Enter amount
7. For recipient name and account name, I'm unable to enter

### Expected result

I should be able to key the recipient name and account name.

### Actual result

I am unable to key in the recipient name and account name.

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1jUg6M5vHi4drfSJhOiNGZ5riatLpIqtm?usp=sharing

### Device name

Redmi 9

### Android OS

10 QP1A.190711.020

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

purityeverniter@gmail.com

**Comment by johnswekenyi** [comment]
Thank you @Purity-E for this, we have logged it for fixing

**Comment by johnswekenyi** [comment]
Ideally, you should not enter account and name, this should be fetched automatically once you link your account. We are fixing that and we will let you know once done.

**Comment by Purity-E** [comment]
Okay
