### ISSUE TITLE
[Bug]: No response from M-PESA, Telkom or KCB

### ISSUE THREAD

**Issue by liciolentimo** [UseHover/Stax#771]
### Description

I receive a no response error message when checking my balance from either M-PESA, Telkom or KCB. The response time takes about 30 seconds for each transaction and normally cuts out then directs to the default USSD menus.

### Steps to reproduce

1. Open Stax app
2. Check balance of M-PESA/KCB Bank account 
3. Enter PIN
4. Wait for transaction to complete

### Expected result

1. Shorter response time
2. M-PESA Balance should show in app
3. No redirection to default USSD menu

### Actual result

1. Longer response time of sometimes over 30 seconds
2. Redirection to default USSD menu
3. Balance doesn't show in-app

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1Ot5eGm6ukLtS2m11DL9rikZfiLecJYqg?usp=share_link

### Device name

Redmi Note 11

### Android OS

11

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

lentimo@gmail.com

**Comment by johnswekenyi** [comment]
@liciolentimo could you try revoking permissions then regrant those permissions. After that, please run the transactions again and let me know how it goes.

**Comment by liciolentimo** [comment]
@johnswekenyi Revoked and regranted permissions. Same issue persists.

**Comment by johnswekenyi** [comment]
Could you do for me a recording of the bug please? @liciolentimo

**Comment by liciolentimo** [comment]
@johnswekenyi https://drive.google.com/file/d/1y9NRgc66myvQtuihgnqBOKlgW6kuznOW/view?usp=share_link

**Comment by mijiga** [comment]
@liciolentimo are you able to run other Mpesa transactions besides besides the ones you've mentioned above? E.g send money, buy airtime etc

**Comment by johnswekenyi** [comment]
@liciolentimo are you still facing this issue?

**Comment by liciolentimo** [comment]
@johnswekenyi M-PESA seems to work when checking balance but has since stopped showing after the last update. Other M-PESA requests work apart from check balance. Same issue persists for KCB and Telkom

**Comment by davkutalek** [comment]
This issue is generally fix by a device restart. It seems to be a bug in Android itself, there is not much we can do about it, tho it seems to be triggered more when the app crashes.
