### ISSUE TITLE
[Bug]: Send money to bank from MPESA

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#773]
### Description

When sending money from my MPESA account to NCBA bank account, I get a failed transaction.

### Steps to reproduce

1. Open Stax app
2. Tap the send money icon
3.  Select Pay with, MPESA
4.  Select Recipient network, NCBA Bank
5.  Enter the contact account number
6.  Enter the amount
7.  Press the continue button
8.  Press send money now button
9.  Enter MPESA PIN
10.  Press confirm button

### Expected result

A successful transaction

### Actual result

Failed transaction.
We received no response from MPESA. We don't think this transaction worked. Please try again later.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1qTn7qVEj6ia4eSQheSw_t485ZwZLbHBg/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
@rOluochKe is this still an issue on your side?

**Comment by rOluochKe** [comment]
@johnswekenyi all good
