### ISSUE TITLE
[Bug]: Stax app hijacks my screen, clicking back button navigates to all my previous stax screen operations like a website

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#775]
### Description

I had opened slack on my phone when suddenly the screen went black and stax launched. When I swiped left, which is my phones way of clicking the back button to leave this stax screen and go back to slack, it just kept switching to all my previous stax operations like a website would do when you click back button. 

### Steps to reproduce

1. Close stax app
2. Open slack app
3. Stax may or may not hijack screen.
4. Click back button and check behavior. 

### Expected result

When stax app launches itself while on another app (has happened before), clicking the back button clears stax from screen revealing the other app that was on. 

### Actual result

Stax launches itself, and instead of closing after clicking the back button, it navigates through all my other previous screen operations. 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1tSFaTFvYpKFw65uoj9ShMZN7cXAR6FOr/view?usp=drivesdk

### Device name

Huawei y5 2019

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

suemnjeri@gmail.com

**Comment by johnswekenyi** [comment]
THANK YOU @suemnjeri we have logged this for fixing

**Comment by johnswekenyi** [comment]
@suemnjeri the issue of hijacking your screen should now be sorted with latest release v1.18.2, please confirm. However, we are yet to fix the issue of back button navigations.
