### ISSUE TITLE
[Bug]: Pending transaction screen persists after successful completion when making Mpesa transactions

### ISSUE THREAD

**Issue by jnjerin** [UseHover/Stax#777]
### Description

The pending transaction screen persists after the transaction is complete and Mpesa confirmation message has been received when buying airtime, sending money to bank or checking Mpesa balance.

### Steps to reproduce

1. Open the Stax app.
2. On the home screen click on the buy airtime icon.
3. On the “pay with” input field, select M-PESA.
4. On the “recipient network” input field, select Safaricom.
5. Select "myself" as recipient
6. On the “Amount” input field, enter the amount you wish to buy and click continue.
7. Input your Mpesa pin and wait for transaction to complete.

### Expected result

After the transaction is complete, the status should change to successful from pending and update the new balance.

### Actual result

The pending status screen persists even after the transaction completes.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1pXao_00Jk1z7_ACyISnj9HKJCCRp6u-W/view?usp=sharing

### Device name

Redmi Note 9S

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

11f9c800e06a3cea

**Comment by johnswekenyi** [comment]
Relates to #733
