### ISSUE TITLE
Integration broken 

### ISSUE THREAD

**Issue by Purity-E** [UseHover/Stax#781]
### Description

When I try to send money from my bank account to m-pesa account, I get an error of 'Sorry, integration service is broken'.
This error also shows up when I check bank account balance and when buying airtime using bank account.

### Steps to reproduce

1. Open Stax
2. Go to send money
3. Pay with Equity bank
4. Recipient network, enter m-pesa
5. Enter contact number
6. Enter amount

### Expected result

I expect the transaction to go through and money sent from my bank account to m-pesa

### Actual result

The transaction is not going through and I get an error 'Sorry, the integration service is broken'

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1cobIANMUi7LVTX1mp2fiUUO_CbatlMq3?usp=sharing

### Device name

Redmi 9

### Android OS

10 QP1A. 190711.020

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

purityeverniter@gmail.com

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
