### ISSUE TITLE
[Bug]: Sending money to MPESA from bank account

### ISSUE THREAD

**Issue by rOluochKe** [UseHover/Stax#784]
### Description

When sending money from the bank account (NCBA) to MPESA, I get an error

### Steps to reproduce

1. Open the Stax app
2.  On the home screen, select send money option from the icons
3.  Select pay with, NCBA
4.  Select recipient network, MPESA
5.  Enter the contact phone number
6.  Enter the amount
7.  Tap the continue button
8.  Enter PIN

### Expected result

Success with my top-up statement

### Actual result

We need to connect with NCBA before you can use your account(s) for transactions. This won't take long.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1cDmscecJaEHsXpg4_wPPhOipr3-VO16v/view?usp=sharing

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

b300f70d67ca4412

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
