### ISSUE TITLE
[Bug]: Connection with Coop Bank account failed

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#785]
### Description

Any attempt to connect to my coop Bank account fails. 

### Steps to reproduce

1. Open stax app
2. Click on add account
3. Select coop bank
4. Receive a dialog that you have an account connected.
5. Click refresh. Error prompt 'sorry, integration to the service broken' 

### Expected result

App connect to my chosen bank account, and takes me through prompts that actually connects to my bank and I can view balance. 

### Actual result

Is not able to move forward once I select the bank to connect with. Immediately I get the service integration error

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1uBKo2x4B79-aUuvJ0D1gvqWcL0YD9lMR/view?usp=drivesdk 

### Device name

Huawei y5 2019

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

suemnjeri@gmail.com

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
