### ISSUE TITLE
[Bug]: Service integration broken - Equity bank

### ISSUE THREAD

**Issue by Murithijoshua** [UseHover/Stax#786]
### Description

Getting above named error when trying to add Equity to accounts

### Steps to reproduce

steps:

1. Open stax app
2. select add account
3. search and select equity
4. add account number
5. edit equity name
6. tap refresh balance

### Expected result

1. on click refresh balance icon
2. get pin prompt
3. get balce

### Actual result

**sorry, this service integration is broken**

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1cseDwLzIql6NXfcHchUZXUeBtTGvGJ0z/view?usp=sharing

### Device name

Gionee s8s

### Android OS

9.0

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

c074faae6ae398cd

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
