### ISSUE TITLE
[Bug]: Broken Service Integration error is displayed while buying airtime for Equity bank

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#789]
### Description

A Broken Service Integration error is displayed on the buy airtime screen after clicking continue while buying airtime using Equity bank

### Steps to reproduce

1. Open the Stax app
2. Tap the Buy airtime icon on the home screen
3. Select Pay With Equity on the send money screen
4. Select Recipient Network as Safaricom
5. Enter Contact Phone Number
6. Enter Amount in the Amount text box and tap Continue
7. Tap Connect now and pay attention to the error message displayed and the screen.

### Expected result

The transaction to buy airtime successfully continues to completion after taping continue

### Actual result

A Broken Service Integration error is displayed on the buy airtime screen after clicking continue while buying airtime using Equity bank

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1jIxqjZQQYKyqK1Pt6FhMZn2rDXOjAVnr/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
