### ISSUE TITLE
[Bug]: A Broken Service Integration error is displayed while sending money using Equity bank

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#790]
### Description

A broken Service Integration error is displayed on the Send Money screen  after clicking Continue while sending money using Equity bank

### Steps to reproduce

1. Open the Stax app
2. Tap send money icon on the home screen
3. Select Pay With Equity on the send money screen
4. Select Recipient Network as M-PESA
5. Enter Contact Phone Number
6. Enter Amount in the Amount text box
7. Tap on the Account name box to enter the account and tap Continue
8. Tap Connect now and pay attention to the error message displayed and the uneditable Account name box.

### Expected result

The transaction to send money continues to completion after clicking continue

### Actual result

A broken Service Integration error is displayed on the Send Money screen  after clicking Continue while sending money using Equity bank

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1jJFWPKDAgPsJ_Xj8ibs2n5U9Aa-VO9Dg/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
