### ISSUE TITLE
[Bug]: Broken `service integtration on equity transactions`

### ISSUE THREAD

**Issue by kibettheophilus** [UseHover/Stax#792]
### Description

When I try to perform any transaction with equity bank, I get the toast `Sorry this service integration is broken`

### Steps to reproduce

1. Open Stax app
2. Try and link equity bank account
3. You will get a error toast 

### Expected result

Perform transactions using equity bank

### Actual result

No transaction is being done successfully, the there is an error toast

### Device name

Redmi 9A

### Android OS

10

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

5ea7f09261718216

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
