### ISSUE TITLE
[Bug]: Buying Airtime from Coop account fails because my account is linked to 2 accounts

### ISSUE THREAD

**Issue by suemnjeri** [UseHover/Stax#793]
### Description

Buying Airtime from my coop Bank account fails and freezes at the point where I'm supposed to select the account to debit. This is because coop mobile banking links 2 accounts: your actual bank account, and your mcoopcash account which is your phone number. 

### Steps to reproduce

1. Open stax app
2. Select buy airtime
3. Choose coop account as the account to buy with
4. Choose safaricom as the recipient
5. Continue
6. Enter coop pin

### Expected result

The app runs through all the buying Airtime steps successfully 

### Actual result

After entering the coop pin, app starts running but freezes at the point where you choose the account to debit. 

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1u_QG7PnomAMiO9G-bOjiyUMwJsE6hudq/view?usp=drivesdk 

### Device name

Huawei y5 2019

### Android OS

9

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

suemnjeri@gmail.com

**Comment by johnswekenyi** [comment]
@suemnjeri do you still experience this issue?
