### ISSUE TITLE
[Bug]: service intergration is broken

### ISSUE THREAD

**Issue by Kelvin-Wepo** [UseHover/Stax#803]
### Description

I tried performing transactions via app but they were not successiful.  Service intergration is brioken message keeps poping up every time i try transacting via app. However this is not the same case on the USSD.

### Steps to reproduce

1.Open stax app
2.On homescreen tap send money via bank
3.Enter pin
4.Wait for transaction to complete

### Expected result

After performing the transaction i should be able to see on my dashboard transaction is complete

### Actual result

Service intergration message keeps pooping up anytime I transact via app

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1mOSza05fjnbqRuf8uvWDfEANx1aZALeq/view?usp=sharing

### Device name

Huawei Y5 prime

### Android OS

8.1.0

### App version

1.17.1

### Config version

20221108141943

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

kelvinwepo7710@gmail.com

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
