### ISSUE TITLE
[Bug]: Transaction redirects from Sending Money to Check Balance When Sending Money from Equity to MPESA

### ISSUE THREAD

**Issue by Sally-N** [UseHover/Stax#805]
### Description

After inputing your Equity Bank pin inorder to send money to MPESA, the Checking Equity Bank Balance (communicating with USSD service) is the next screen. This then redirects to Check Balance Transaction Status page which shows the transaction status as failed and transaction type as Check balance

### Steps to reproduce

1. Open Stax App
2. Tap Send Money Icon
3. On the Send Money Screen, select pay with  Equity Account
4. Recipient network select MPESA
5. Enter phone number(your's or someone else's)
6. Enter amount above 10ksh
7. Click Continue
8. Enter Bank Pin and Click Confirm

### Expected result

The next screen should be Send Money screen(communicating with USSD service) which will then redirect to the Send Money Transaction status which will show transaction type as Send Money

### Actual result

The next screen is Check Balance screen(communicating with USSD service) which will then redirects to Check Balance Transaction Status page which shows the transaction status as failed and transaction type as Check balance

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1NqGDj5zmgbxUDFP062-E0DK9oJHP82eD/view?usp=sharing

### Device name

Samsung A22

### Android OS

12

### App version

1.17.3

### Config version

20221109082804

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

snzungula@gmail.com

**Comment by johnswekenyi** [comment]
Thank you @Sally-N for this, we are working to sort the configuration issue

**Comment by johnswekenyi** [comment]
@Sally-N this should be fixed now with release 1.18.2
