### ISSUE TITLE
[Bug]: Transaction redirects from Buy Airtime to Check Balance When Buying Airtime with Equity bank to Safaricom

### ISSUE THREAD

**Issue by Sally-N** [UseHover/Stax#806]
### Description

After inputing your Equity Bank pin inorder to buy airtime with Equity Bank to Safaricom, the Checking Equity Bank Balance (communicating with USSD service) is the next screen. This then redirects to Check Balance Transaction Status page which shows the transaction status as failed and transaction type as Check balance

### Steps to reproduce

1. Open Stax app.
2. On the home screen click on the Buy airtime icon.
3. On the pay with input field, select Equity bank.
4. On the recipient network input field, select Safaricom.
5. Next , on the Contact phone number input field, enter your phone number
6. On the “Amount” input field, enter the amount above 10ksh and click continue.
7. When prompted with the “Finish importing account” modal click connect now.
8. Pay attention to the transaction details page.

### Expected result

The next screen should be Buy Airtime with MPESA screen(communicating with USSD service) which will then redirect to the Buy Airtime Transaction status which will show transaction type as Buy AirTime

### Actual result

The next screen is Check Balance screen(communicating with USSD service) which will then redirects to Check Balance Transaction Status page which shows the transaction status as failed and transaction type as Check balance

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1NuAsVevqAn7QJwx9UCMdKhu-tVNrmQDp/view?usp=sharing

### Device name

Samsung A22

### Android OS

12

### App version

1.17.3

### Config version

20221109082804

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

snzungula@gmail.com

**Comment by davkutalek** [comment]
@Sally-N it looks like your account list is messed up due to issues in our previous app version/equity configuration. Could you please uninstall or clear data and then re-install?

**Comment by Sally-N** [comment]
@davkutalek After clearing cache, my transactions are failing. I'm gonna uninstall then re-install

**Comment by Sally-N** [comment]
@davkutalek after re-installing check balance, send money and buy airtime are still failing
