### ISSUE TITLE
[Bug]: Buy airtime transaction fails when using Equity bank 

### ISSUE THREAD

**Issue by jnjerin** [UseHover/Stax#808]
### Description

Transaction fails when buying airtime with Equity bank returning a FAIL status message stating no response from Equity bank.

### Steps to reproduce

1. Open the Stax app.
2. On the home screen click on the buy airtime icon.
3. On the “pay with” input field, select the Equity bank account.
4. On the “recipient network” input field, select Safaricom.
5. On the “Contact phone number” input field, enter your phone number.
6. On the “Amount” input field, enter the amount you wish to buy and click continue.
7. When prompted with the “Finish importing account” modal click connect now.
8. Select SIM to use , enter PIN and observe the transaction process.

### Expected result

The transaction prompts for PIN then completes and recipient gets airtime purchased with a SUCCESS status message.

### Actual result

The transaction proceeds to complete and returns a FAIL status with no response from Equity bank error message.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1qI6CMR3KmV__TV6un4Rxm0sgBP54UdpX/view?usp=sharing

### Device name

Redmi Note 9S

### Android OS

10

### App version

1.17.3

### Config version

20221109130723

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

11f9c800e06a3cea

**Comment by johnswekenyi** [comment]
Relates to #806
