### ISSUE TITLE
[Bug]: Partial response from equity

### ISSUE THREAD

**Issue by Murithijoshua** [UseHover/Stax#811]
### Description

checking Equity balance returns failed status

### Steps to reproduce

1. open stax app
2. select equity under accounts section
3. click check balance

### Expected result

SMS/alert with bank balances

### Actual result

**We received only a partial response from equity bank. We don't think this transaction worked. please try Again**

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1KVhiMn_cYaLDIYhk4G2Drv1gl8qr3h4t/view?usp=sharing

### Device name

Gionee s8s

### Android OS

9.0

### App version

1.17.3

### Config version

20221109082804

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

c074faae6ae398cd

**Comment by davkutalek** [comment]
@Murithijoshua you do not appear to be registered to use Equity USSD service. Can you run the USSD session manually?

**Comment by Murithijoshua** [comment]
@davkutalek I will register with another line and line and try again

**Comment by johnswekenyi** [comment]
@Murithijoshua is this still an issue for you?
