### ISSUE TITLE
[Bug]: Service Intergration failed

### ISSUE THREAD

**Issue by Kelvin-Wepo** [UseHover/Stax#813]
### Description

I get the above error when connecting to banks

### Steps to reproduce

1. Open stax app
2. select add account
3. search and select equity
4. add account number
5. edit equity name
6. tap refresh balance

### Expected result

1.on click refresh balance icon
2. get pin prompt
3. get balance

### Actual result

sorry, this service integration is broken

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1t_e_Ko6C3ZfLw7RknrCw6FiLyz6ISX_J/view?usp=sharing

### Device name

Huawei Y5 prime

### Android OS

8.1.0

### App version

1.17.3

### Config version

20221109191508

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

kelvinwepo7710@gmail.com

**Comment by johnswekenyi** [comment]
This has been fixed with the new release that we will be putting out early next week.
