### ISSUE TITLE
[Bug]: A Finish Importing Account prompt is displayed while buying airtime using Equity bank

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#814]
### Description

A Finish Importing Account prompt is displayed on the buy airtime screen after tapping Continue while buying airtime using Equity bank

### Steps to reproduce

1. Open the Stax app
2. Tap the Buy airtime icon on the home screen
3. Select Pay With Equity on the send money screen
4. Select Recipient Network as Safaricom
5. Enter Contact Phone Number and tap Continue
7. Pay attention to the message on the prompt.

### Expected result

The transaction to buy airtime continues to completion successfully after tapping continue

### Actual result

A Finish Importing Account prompt is displayed on the buy airtime screen after tapping Continue while buying airtime using Equity bank

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1lyAbUn0gqwTQ9CabPmPykRoRGEIQEnu-/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### App version

1.17.3

### Config version

20221108184805

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by davkutalek** [comment]
@hilderbrandtjohn this is intended behavior. We need to check balance with equity to find out if you have multiple accounts. Once you balance is updated does it allow you to proceed with the purchase?

**Comment by hilderbrandtjohn** [comment]
> @hilderbrandtjohn this is intended behavior. We need to check balance with equity to find out if you have multiple accounts. Once you balance is updated does it allow you to proceed with the purchase?

@davkutalek The issue repeats itself even after running the check balance. (I did the transaction more than once on the recirding)It still prompts the same message on subsequent transactions. Also,the balance is not returned. The transaction completes but the balance page presents a pending status.

**Comment by davkutalek** [comment]
@hilderbrandtjohn we fixed the configuration issues with equity check balance, so it should confirm correctly now. Once confirmed it should allow you to proceed.

**Comment by hilderbrandtjohn** [comment]
@davkutalek I have tested it and all transactions now run to completion. The wait time is a bit long but they all run
