### ISSUE TITLE
[Bug]: The app keeps Disconnecting

### ISSUE THREAD

**Issue by Kelvin-Wepo** [UseHover/Stax#815]
### Description

Every time I try Making transactions, the app keeps asking to the connected even after connecting it still asks to be connected whenever I want to perform a transaction

### Steps to reproduce

1. Open stax app
2. select add account
3. search and select equity
4. add account number
5. edit equity name
6. tap send money

### Expected result

The app should directly send money to the selected recepient  without asking for reconnection since it's connected.

### Actual result

After inputing money to send, the app asks for reconnectiong again before performing transaction

### Device name

Huawei Y5 prime

### Android OS

8.1.0

### App version

1.17.3

### Config version

20221109191508

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

kelvinwepo7710@gmail.com

**Comment by johnswekenyi** [comment]
@Kelvin-Wepo this bug is not very clear, could you please add a recording of what the bug looks like then we can review from our end?
