### ISSUE TITLE
[Bug]: Error is displayed after tapping continue while sending money with equity

### ISSUE THREAD

**Issue by hilderbrandtjohn** [UseHover/Stax#822]
### Description

A < This service can not be used to buy airtime > error is displayed on the send money screen after tappping continue while sending money with equity bank

### Steps to reproduce

1. Open the Stax app. 
2. Tap send money icon.
3. Select pay with Equity Bank. 
4. Enter the contact phone number. 
5. Enter the amount
6. Tap Continue 
7. Pay attention to the message displayed below the pay with box

### Expected result

Transaction to send money continues successfully to completion after tapping continue. 

### Actual result

A < This service can not be used to buy airtime > error is displayed on the send money screen after tappping continue while sending money with equity bank

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1mgc8ns1GWfQ6sMnhftiPeBtflobysfFP/view?usp=drivesdk

### Device name

Samsung Galaxy A32

### Android OS

12

### App version

1.18.0

### Config version

20221111081009

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

bc34b750f5749d4a

**Comment by johnswekenyi** [comment]
@hilderbrandtjohn this should be fixed now with release 1.18.2
