### ISSUE TITLE
[Bug]: Service cannot be used for send money when using M-PESA to send money to Bank Account message

### ISSUE THREAD

**Issue by Sally-N** [UseHover/Stax#831]
### Description

A warning message is displayed below pay with input on the send money screen when attempting to send money from M-PESA to bank account

### Steps to reproduce

1. Open Stax
2. Tap the Send Money Icon
3. On the Send Money Screen, Select pay with M-PESA option
4. Enter phone number to send to
5. Enter amount
6. Tap the Continue button

### Expected result

The next screen will prompt for MPESA pin

### Actual result

A warning message is displayed below pay with input on the send money screen when attempting to send money from M-PESA to bank account

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1_yHuSLNhxbAiMUUR1ml1mXbNaN5e3LnM/view?usp=sharing

### Device name

Samsung A22

### Android OS

12

### App version

1.18.2

### Config version

20221122200424

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

snzungula@gmail.com

**Comment by davkutalek** [comment]
This should be fixed in more recent configs/app versions
