### ISSUE TITLE
[Bug]: App keeps crashing when launching

### ISSUE THREAD

**Issue by larrymiami** [UseHover/Stax#893]
### Description

The app keeps crashing a few seconds after opening it.

### Steps to reproduce

1. Open the Stax app.

### Expected result

The app opens and allows one to use it.

### Actual result

It crashes and closes every time it opens.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1xGumNgj4AV7Ee84pobh5Ys_vcEjZXzUv/view?usp=sharing

### Device name

Nokia 3.2

### Android OS

11

### App version

1.18.9

### Config version

N/A

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

ae3a4fb4d6502412

**Comment by davkutalek** [comment]
This will be fixed by our next update
