### ISSUE TITLE
[Bug]:  The app does not have an update button on playstore

### ISSUE THREAD

**Issue by Kelvin-Wepo** [UseHover/Stax#895]
### Description

The  app does not have an update button on google Play store which makes it very difficult to update to the new version.

### Steps to reproduce

1. On your phone Navigate through Playstore.
2. Search for Stax  app on playstore

### Expected result

I expect to find an update button on the app inorder to update the app to the latest version.

### Actual result

There is no update button on the app and it's currently in the previous version hence making it difficult to update it to the latest version

### Link to screenshots/screen recordings

https://drive.google.com/drive/folders/1-hdGUlFZpDIDSlwCjogrLWKCwPcZvqAA

### Device name

Huawei Y5 prime

### Android OS

8.1.0

### App version

1.17.3

### Config version

20221109191508

### Is your phone dual SIM or single SIM?

Single SIM

### Which telco are you using for this test?

Safaricom

### Stax device ID or email address

kelvinwepo7710@gmail.com

**Comment by davkutalek** [comment]
This is cause we haven't rolled the update out to 100% of users yet. Still working out a few kinks, should be ready soon
