### ISSUE TITLE
[Bug]: Pending transaction status persists after transaction completes when checking Mpesa balance

### ISSUE THREAD

**Issue by jnjerin** [UseHover/Stax#963]
### Description

The pending transaction status persists after the transaction is complete and Mpesa confirmation message has been received when  checking Mpesa balance.

### Steps to reproduce

1. Open Stax app
2. On the home screen tap Check Balance for M-Pesa account
3. Input your Mpesa PIN
4. Wait for transaction to complete

### Expected result

After the transaction is complete, the status should change to successful from pending and update the new balance.

### Actual result

The pending status screen persists even after the transaction completes and Mpesa message has been received.

### Link to screenshots/screen recordings

https://drive.google.com/file/d/110E7ABQjf7EmRyvB8-aDWE8A25vCUjvH/view?usp=sharing

### Device name

Redmi Note 9S

### Android OS

11

### App version

1.19.6

### Config version

20230223000057

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this transaction?

Safaricom

### Stax device ID or email address

njerijoan24@gmail.com

**Comment by jimiegha** [comment]
Cc @davkutalek

**Comment by jnjerin** [comment]
It's okay now. And status changes immediately.
