### ISSUE TITLE
[Bug]: Buying airtime with Equity bank  transaction redirects to check balance 

### ISSUE THREAD

**Issue by jnjerin** [UseHover/Stax#964]
### Description

When buying airtime with Equity bank, the transaction redirects to check balance and completes with a balance update.

### Steps to reproduce

1. Open the Stax app.
2. On the home screen click on the buy airtime icon.
3. On the “pay with” input field, select Equity Bank.
4. On the “recipient network” input field, select Safaricom.
5. Select "myself" as recipient
6. On the “Amount” input field, enter the amount you wish to buy and click continue.
7. Input your Equity bank PIN.
8. Observe the transaction.

### Expected result

The recipient receives the airtime and sms confirmation. The transaction completes and updates bank balance. 

### Actual result

The transaction completes with a bank balance update and recipient does not receive airtime or sms confirmation

### Link to screenshots/screen recordings

https://drive.google.com/file/d/1186ZP1OsyxqGhL8UsbilCp9W2O4hrbVO/view?usp=sharing

### Device name

Redmi Note 9S

### Android OS

11

### App version

1.19.6

### Config version

20230223000057

### Is your phone dual SIM or single SIM?

Dual SIM

### Which telco are you using for this transaction?

Safaricom

### Stax device ID or email address

njerijoan24@gmail.com

**Comment by jimiegha** [comment]
@jnjerin Can you try the transaction again and let me know the outcome?
